### ISSUE TITLE
Function that prints the first reason why a project is out of date

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1003]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

I often try to move a project from one computer (i.e. a server) to another only to find that it becomes out-of-date on the new machine and I don't know why.

It would be nice to have a convenience function that prints the first reason why a project is out-of-date. I guess it would be the dependency profile that you would print.

I have found this problem many times with collaborative projects as well.

**Comment by wlandau** [comment]
What specifically does `deps_profile()` show when this happens? We might be able to narrow it down with a small project if you can share one.

Otherwise, I am afraid `deps_profile()` is the closest we can get without inflating storage and invalidating everyone's workflows, re #496 and #497.

`drake` does not remember the hash of every single dependency. Rather, it stores a [composite dependency hash](https://github.com/ropensci/drake/blob/a6f7fa7a00af97dc872ab20154cfd5659a9f81f4/R/drake_meta_.R#L74-L79) (a hash of hashes). In other words, the information for a more specific `deps_profile()` is not available. We would have to store a lot more hashes. This could interfere with performance for workflows with a lot of targets, and it would definitely be a breaking change.

**Comment by kendonB** [comment]
Yeah I was thinking of something like: `deps_profile(target = outdated(this_config)[1], this_config, character_only = TRUE)` which actually isn't that bad.

**Comment by wlandau** [comment]
Ah, I misunderstood what you were asking for. Yeah, I do not think it is worth adding that one-liner to `drake` itself.
