### ISSUE TITLE
max_expand and dynamic subtargets

### ISSUE THREAD

**Issue by hansvancalster** [ropensci/drake#1050]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [ ] Consider instead posting to [Stack Overflow](https://stackoverflow.com) under the [`drake-r-package` tag](https://stackoverflow.com/tags/drake-r-package).

## Question

First: a big thank you for this amazing package!

I recently tried dynamic branching in combination with `max_expand`, but it appears `max_expand` only works for static targets. Would it be possible to make `max_expand` work for dynamic subtargets as well?

**Comment by wlandau** [comment]
Great idea! Let's do that.

I think `max_expand` for dynamic branching will be different in a couple ways: 

1. It will need to be an argument of `make()` and `drake_config()` rather than `drake_plan()`.
2. To avoid confusion, I think the dynamic `max_expand` should select the first few targets instead of trying to spread out on a grid. Dynamic branching has cryptic names, so I think this approach will be clearer.

**Comment by hansvancalster** [comment]
Thanks for considering this! My current workaround for experimentation in projects with a large number of dynamic sub-targets is just to temporarily restrict the number of groups of the grouping variable used in dynamic targets. This works without too much hassle, but it would be nice for users to have something similar to `max_expand`. 

Also the section in the help file `?drake::drake_plan` about `max_expand` should probably mention that this is only for static branching.

**Comment by wlandau** [comment]
Now implemented.

> Thanks for considering this! My current workaround for experimentation in projects with a large number of dynamic sub-targets is just to temporarily restrict the number of groups of the grouping variable used in dynamic targets. This works without too much hassle, but it would be nice for users to have something similar to max_expand.

Agreed, I want to make this easy. I think it is really important to be able to scale up and down quickly. In fact, my first package on CRAN did exactly this: https://github.com/wlandau/downsize.

> Also the section in the help file ?drake::drake_plan about max_expand should probably mention that this is only for static branching.

Done.

**Comment by hansvancalster** [comment]
Great:+1: Will try this tomorrow.

**Comment by wlandau** [comment]
Awesome! So glad you are trying out dynamic branching. I really helps to have real-world testers before things like this go to CRAN.

NB I extended the manual to discuss this [here](https://github.com/ropenscilabs/drake-manual/blob/f200b5e16329272b8bbb2e049b406267689d35cf/dynamic.Rmd#L217). [Travis](https://travis-ci.org/ropenscilabs/drake-manual/builds/608217482?utm_source=github_status&utm_medium=notification) should push it [online](https://ropenscilabs.github.io/drake-manual/dynamic.html) in a few minutes.

**Comment by hansvancalster** [comment]
Tried it on my project and it works as expected. Just one afterthought, I have both dynamic and static targets and I wonder if `max_expand` inside `make` and `drake_config` could be adjusted in a way that both the number of dynamic _and_ static targets will be limited. In that way, the user needs to set it in only one place (possible `max_expand` could be a size two vector in that case). Not a big deal, but it would also simplify the explanations in the manual.

Very good addition to the manual. Thanks!

**Comment by wlandau** [comment]
I considered unifying the `max_expand`s, but since static and dynamic targets get expanded in to totally different places, I think they really do belong as separate arguments.

If we were to have only one `max_expand`, it would have to go in `drake_plan()` only, and the plan would somehow have to carry the `max_expand` value.  

Plus, we may want to expand dynamic and static targets differently. Static expansion produces large graphs and slow startup times for `make()`, and we can create a lot more dynamic targets without running into these performance issues.

**Comment by hansvancalster** [comment]
Thanks for clarifying. I agree. I think most users will want the benefit of a readable graph and therefore use dynamic expansion for cases where many subtargets are created and restrict static expansion to cases that result in few targets. In these cases it will usually suffice to only set `max_expand` to a low value inside `map` or `drake_config` for fast experimentation.
