### ISSUE TITLE
Run code after all targets build

### ISSUE THREAD

**Issue by vrodriguezf** [ropensci/drake#1051]
Hi,

I see that `make` has an argument `prework` to execute expressions before targets build. Is there anything similar but applicable to the end of the build?

Thanks!

**Comment by wlandau** [comment]
`drake` has `prework` to make sure all the targets get the correct global options etc. before they build. The intent is to help set up parallel workers (e.g. `make(parallelism = "future")`) because those workers do not always automatically get everything they need from the global environment. After `make()` is done, stuff like this is no longer necessary, so I do not plan to add anything like `prework` for after `make()`. 

Workarounds:

1. If your call to `make()` is [stored in a script](https://ropenscilabs.github.io/drake-manual/projects.html#code-files) (e.g. `make.R`) simply include the end-of-build code at the end. 
2. Define a new target that depends on everything at the end of the pipeline and give it `trigger(condition = TRUE)` to make sure it always runs. Details: https://ropenscilabs.github.io/drake-manual/triggers.html.
