### ISSUE TITLE
combining in-memory data.frame targets into a disk.frame

### ISSUE THREAD

**Issue by brendanf** [ropensci/drake#1070]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [X] Consider instead posting to [Stack Overflow](https://stackoverflow.com) under the [`drake-r-package` tag](https://stackoverflow.com/tags/drake-r-package).

## Question

Is there an efficient way to combine data from multiple targets into a `disk.frame`? My two issues are:
 1) The combined target is a `disk.frame` because it is too big to fit in memory; I don't want to have to load everything into memory in order to create the `disk.frame`.
 2) The `disk.frame` is a directory of *.fst files; my individual targets are *.fst files in the cache.  There is a lot of space being taken by these files (more than fits in RAM, although the files at least are compressed) and I would prefer not to save all the same data in all the same format twice.

It's my understanding that the `disk.frame` target is stored as a directory in the cache, where each shard is an `fst` file. It seems like at the back end, there would be the possibility to make a `disk.frame` directory containing symbolic links to other results from the cache.  I'm not clear how I could do that in user code; it seems that one of the goals of the drake cache is to abstract away the storage mechanism, so I'm not aware of any way to find out the actual file name which is storing a particular fst target.  Otherwise, something like this might work:

```
combine_diskframe <- function(..., dir = drake_tempfile()) {
  shards <- rlang::ensyms(...)
  for (s in shards) {
    shardfile <- get_target_file(rlang::expr_text(s)) # if this function existed
    file.symlink(shardfile, file.path(dir, basename(shardfile)))
  }
  disk.frame::disk.frame(dir)
}
```

This function could then be used in a target using `transform = combine` and `memory_strategy = "none"`.

Is there a way this could work?  Is there a better way to go about it?

**Comment by wlandau** [comment]
Cool idea, @brendanf! Your `combine_diskframe()` function looks like it should be super fast. The biggest snag is `get_target_file()`. I am reluctant to write such a general function because I think it would be dangerous for most users. But since you know what you are doing, you can get the file yourself using the cache.

``` r
library(drake)
library(fst)
plan <- drake_plan(
  x = target(
    data.frame(x = seq_len(4), y = letters[seq_len(4)]),
    format = "fst"
  ),
  y = 123
)
make(plan)
#> target y
#> target x
cache <- drake_cache() # a decorated storr

# files with special formats like fst
# If you use the cache in the plan, be sure to ignore the cache itself,
# e.g. ignore(cache)$file_return_key("x")
# "file <- cache$file_return_key("x")
read_fst(file)
#>   x y
#> 1 1 a
#> 2 2 b
#> 3 3 c
#> 4 4 d

# storr's default RDS files
hash <- cache$get_hash("y")
file <- file.path(cache$driver$path, "data", paste0(hash, ".rds"))
readRDS(file)
#> [1] 123
```

<sup>Created on 2019-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think `fst` files should theoretically work with what you have in mind. Additional confirmation from @xiaodaigh might be nice on a couple points:

1. Are there any special considerations or dangers if a `disk.frame` is a directory full of sym links to `fst` files?
2. Is it possible to create a `disk.frame` from a directory of RDS files (or sym links to them) or should we stick to `fst` and CSV formats for the input shards? 

In any case, those sym links should only point to files inside the cache. If the cache starts to accrue unconventional external dependencies, then it will not be valid when shipped to another computer.

Please keep me posted on this workaround. If it is a common enough pattern, we might eventually want to build API functions to handle it more smoothly.

**Comment by xiaodaigh** [comment]
> 1. Are there any special considerations or dangers if a `disk.frame` is a directory full of sym links to `fst` files?

As long as `list.files` can see them as having extension `.fst` then it's fine.

> 2\. Is it possible to create a `disk.frame` from a directory of RDS files (or sym links to them) or should we stick to `fst` and CSV formats for the input shards?

Yes. But there isn't a convenient function yet like `as.disk.frame` or `csv_to_disk.frame`. One would need a function like `lapply` to read the files and use `add_chunk` to add the chunks to a disk.frame. 

Much much later, we will have a multi-backend disk.frame where a disk.frame can be backed by fst, rds, parquent, or CSV files. But it's in the backlog of development.

**Comment by wlandau** [comment]
Thanks, @xiaodaigh. 

Confirmed: in this workaround, at least for now, dependencies of these special `combine()` `disk.frame` targets should have `format = "fst"` (which is good practice anyway).

Also, in the next release of `drake`, you will no longer need to explicitly `ignore()` caches that show up in commands (#1071).

**Comment by brendanf** [comment]
@xiaodaigh It looks like symlinks don't work properly in a `disk.frame`;  `nchunks.disk.frame` only detects normal files:

``` r
function (df, skip.ready.check = FALSE, ...) 
{
  fpath <- attr(df, "path")
  if (is.dir.disk.frame(df)) {
    return(length(fs::dir_ls(fpath, type = "file")))
  }
  else {
    return(1)
  }
}
```

I'm not sure if that's something you would consider changing?

In the meantime, it seems to work with hard links (on file systems that support them).

**Comment by xiaodaigh** [comment]
Definitely, let me research the relevant functions. I wonder if `list.files` work better
