### ISSUE TITLE
Question: How do I use map like lapply?

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1087]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [X] If you think your question has a quick and definite answer, consider posting to [Stack Overflow](https://stackoverflow.com) under the [`drake-r-package` tag](https://stackoverflow.com/tags/drake-r-package). (If you anticipate extended follow-up and discussion, you are already in the right place!)

## Question

I want to use the DSL to work similarly to `purrr::pmap()` or `lapply()`, but I'm coming up short in my understanding.

In general, I want to apply a function to all list elements for another target (the fact that it's another target may be my issue, I think).  A similar way that I'd do it in non-drake paradigms are:

```r
library(purrr)
foo <- as.list(1:10)
list_plus <- function(x, y) x[[1]] + y
pmap(.l=list(x=foo), .f=list_plus, y=1)
lapply(foo, "+", 1)
```

Both of those make a list with elements valued as `2:11`.

I thought that the equivalent in `drake` would be something like the following, but it doesn't give the correct plan:

```r
library(drake)

test_plan <-
  drake_plan(
    foo=as.list(1:10),
    bar=
      target(
        list_plus(foo, 1),
        transform=map(!!foo)
      )
  )

make(test_plan)
```

With that attempt, I get the following warning which indicates that I'm not getting what I'm looking for:

```
Warning message:
A grouping or splitting variable for target "bar" is missing or undefined. Transformation skipped and target deleted. 
```

Is there a way to use `map()` with a value that is also a target like `foo` in my example above?

**Comment by wlandau** [comment]
You are almost there. For the static branching interface (`target(transform = ...)`), `foo` cannot be a target.. Static transforms can only take variables that exist in advance.

``` r
library(drake)
foo <- as.list(seq_len(4))
drake_plan(
  bar = target(
    list_plus(foo, 1),
    transform = map(foo = !!foo)
  )
)
#> # A tibble: 4 x 2
#>   target command         
#>   <chr>  <expr>          
#> 1 bar_1L list_plus(1L, 1)
#> 2 bar_2L list_plus(2L, 1)
#> 3 bar_3L list_plus(3L, 1)
#> 4 bar_4L list_plus(4L, 1)
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If you want `foo` to be a target, you might consider [dynamic branching](https://books.ropensci.org/drake/dynamic.html) (just released with version 7.8.0 on CRAN).

``` r
library(drake)
  
add_things <- function(x, y) {
  x[[1]] + y
}
  
plan <- drake_plan(
  foo = as.list(seq_len(4)),
  bar = target(
    add_things(foo, 1),
    dynamic = map(foo)
  )
)

make(plan)
#> target foo
#> dynamic bar
#> subtarget bar_dac543b9
#> subtarget bar_37ec99be
#> subtarget bar_e63637e0
#> subtarget bar_df839848
#> aggregate bar

readd(bar)
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3
#> 
#> [[3]]
#> [1] 4
#> 
#> [[4]]
#> [1] 5
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
Thank you for the quick response!

**Comment by kendonB** [comment]
@wlandau Is there a way to get `map` to subset the list using `[[` rather than `[`? This is closer to the behavior of `purrr::map` and `lapply`

**Comment by wlandau** [comment]
Maybe it would have made more sense at first glance, but that would require a breaking change at this point. And as I explain below, I am sticking by the original decision anyway.

A fundamental assumption of dynamic branching is to treat everything as a vector and subset everything as a vector. The closest precedent is [`vctrs`](https://github.com/r-lib/vctrs), which I very nearly used verbatim.

``` r
i <- seq_len(2)
vec <- letters[seq_len(3)]
lst <- as.list(vec)
dtf <- mtcars

library(vctrs)
vec_slice(vec, 1)
#> [1] "a"
vec_slice(vec, i)
#> [1] "a" "b"
vec_slice(lst, 1)
#> [[1]]
#> [1] "a"
vec_slice(lst, i)
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b"
vec_slice(dtf, 1)
#>           mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> Mazda RX4  21   6  160 110  3.9 2.62 16.46  0  1    4    4
vec_slice(dtf, i)
#>               mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

<sup>Created on 2019-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`vctrs`-like subsetting is clean and consistent in its own right. Whether you take one element or multiple elements, and whether you start with a list or atomic type or data frame, you're always getting the same kind of vector you started with. That gives us a powerful combination of internal consistency and flexibility. We totally abstract away the subsetting mechanics and still have confidence that we're getting predictable return types, even if they're not always the most convenient. This idea is a foundational piece of dynamic branching, and it's one of the major reasons the implementation turned out so well.

Maybe this deserves a clearer explanation in the docs, e.g. https://github.com/ropensci-books/drake/blob/master/dynamic.Rmd. PRs always welcome.
