### ISSUE TITLE
Print x / N for subtargets?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1102]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

In cases where the number of subtargets for a given dynamic target is known, it would be great to print something like 

```r
subtarget x/N target_name_hash
```

to give an indicator of progress. Is this feasible? Even when N is unknown you could still print x.

P.S. I have tried out the dynamic branching version of map with clustermq and SLURM and it seems to be working great!

**Comment by wlandau** [comment]
Glad to hear dynamic branching is working well for you.

Sorry, but I hesitate to add more to the console messages because things tend to get visually busy very easily and there is extra bookkeeping involved that could slow us down (particularly for `x`). Believe it or not, printing to the console adds a surprising amount of overhead if the number of targets is large and each target is quick. I see it all the time in profiling studies nowadays. I suspect that assigning and keeping track of integer sub-target indices will have a similar cost.

**Comment by kendonB** [comment]
I would still urge you to consider some optional progress indication.

**Comment by wlandau** [comment]
How do you feel about `progress()`, `running()`, and `failed()`?

**Comment by kendonB** [comment]
I haven't used them until now but there's definitely value there. 

However, those functions can only tell me about what has happened or is going on now. To really know progress we also need to know how much is to come.

Is there any feaible way to have drake also know N above? Even in a limited number of cases or as a guess? Or for a particular target that has already started and is currently calculating subtargets?

**Comment by wlandau** [comment]
It does, actually.

https://github.com/ropensci/drake/blob/daf204fc7fa0bc4ea7547e9747c57581f02c9afa/R/dynamic.R#L262

Right under [here](), we could insert `config$logger$minor("register", ndeps, "subtargets", target = target)`.

**Comment by wlandau** [comment]
That way, you will see it in the `console_log_file`.

**Comment by wlandau** [comment]
Implemented.
