### ISSUE TITLE
Updating rstan and StanHeaders invalidates targets?

### ISSUE THREAD

**Issue by crsh** [ropensci/drake#1111]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] If you think your question has a quick and definite answer, consider posting to [Stack Overflow](https://stackoverflow.com) under the [`drake-r-package` tag](https://stackoverflow.com/tags/drake-r-package). (If you anticipate extended follow-up and discussion, you are already in the right place!)

## Question

As alluded to a couple of days ago [on Twitter](https://twitter.com/FrederikAust/status/1203974326355148800), I recently witnessed invalidation of some of my targets after updating `rstan` and `StanHeaders`. I wonder whether this is expected behavior (because it took me by surprise). My basic plan looks something like the following:

~~~r
options(mc.cores = parallel::detectCores() - 1)
rstan::rstan_options(auto_write = TRUE)

drake_env <- new.env(parent = globalenv())

normal <- "
data {
  vector[100] y;
}

parameters {
  real mu;
  real<lower=0> sigma;
}

model {
  y ~ normal(mu, sigma);
}"

my_plan <- drake_plan(
  data = list(y = rnorm(100))
  , stan_model = !!normal
  , normal_model = rstan::stan_model(
    model_code = stan_model
  )
  , normal_samples = rstan::sampling(
    object = normal_model
    , data = data
    , chains = 1
  )
)

drake_conf <- drake_config(
  my_plan
  , verbose = 2
  , cache = new_cache("my_cache")
  , envir = drake_env
)

vis_drake_graph(drake_conf)
drake_conf
~~~

I'm running the plan via `drake::r_make()`. If I remember correctly, I think I was using `rstan` 2.13.2 prior to the update.

I should say, I haven't been able to check whether I can reproduce the problem with this boiled down plan, because at this time I cannot risk rerunning all of my models again. I hope the plan itself may give some insight.

**Comment by wlandau** [comment]
I think I know what happened. Because you prefixed the `stan_model()` function with `rstan::` in your code, `drake` decided to track the `rstan_model()` function for changes.

![Screen Shot 2019-12-12 at 8 50 58 AM](https://user-images.githubusercontent.com/1580860/70717668-d28b5f00-1cbc-11ea-9a33-3a39019b6860.png)

When you updated `rstan`, the `rstan::stan_model()` function changed on your system. In `rstan` 2.19.2, `digest::digest(drake:::standardize_imported_function(rstan::stan_model))` returns `"6fb9ef63c390960f6240365e3705ae03"`. I suspect this is a different value for 2.13.2 (though I cannot install it and thus cannot check to be sure.) If I am right, then, the changed function invalidated the `normal_model` target. When you compiled `normal_model` again, you got a different result, because in-memory compiled Stan models are brittle, which triggered an update to `normal_samples`.

A side note: I was worried that compiled Stan models would be [too brittle to serve as good targets](https://books.ropensci.org/drake/plans.html#how-to-choose-good-targets), but apparently we're okay: if we save the model as an RDS file, we get the same value back when we load it in a different R session.

```r
> library(digest)
> library(drake)
> x <- readd(normal_model)
> digest(x)
[1] "54837dfc7f1f6399088ab8b589438d2e"
> saveRDS(x, "model.rds")

Restarting R session...

> library(digest)
> digest(readRDS("model.rds"))
[1] "54837dfc7f1f6399088ab8b589438d2e"
```

And models compiled in different sessions appear to remain valid.

```r

Restarting R session...

> library(drake)
> library(rstan)
> model <- readd(normal_model)
> sampling(model, data = list(y = rnorm(100)), chains = 1)

SAMPLING FOR MODEL 'a3b2c6619c69f6a2a887fc97c0fc22d0' NOW (CHAIN 1).
Chain 1: 
...
```

But different versions of the `rstan` package could compile models differently, so it is good that refit the model. Going forward, I recommend [`renv`](https://github.com/rstudio/renv) to lock down your package environment. (If you have used `packrat` in the past and found it slow, I will say that `renv` is much faster and nicer to use.)

**Comment by crsh** [comment]
Great, that explains a lot. Thanks a lot for the clarification!

**Comment by wlandau** [comment]
Glad to help. One more thing: I do not know what will happen if you transfer the project and its cache to a different system with a different toolchain. The compiled model may no longer work there if you need to run it.
