### ISSUE TITLE
Dynamic branching does not retain class of data.table or data.frame?

### ISSUE THREAD

**Issue by mik3y64** [ropensci/drake#1116]
Dynamic branching does not retain class of data.table?

I am testing dynamic branching with data.table and got some errors in my project. I managed to trace the errors and found out it was the issue with returned class of dynamic branching.

```r
library(drake)
packageVersion("drake")
# [1] ‘7.8.0.9000’
library(tidyverse)
library(data.table)

plan <- drake_plan(
  data.table = mtcars[by, ] %>% as.data.table(),
  tibble.data = mtcars[by, ] %>% as_tibble(),
  by = seq_len(2),
  data.table.by = target(
    data.table,
    dynamic = group(data.table, .by = by)
  ),
  tibble.data.by = target(
    tibble.data,
    dynamic = group(tibble.data, .by = by)
  )
)

make(plan)

class(readd(data.table.by))
# [1] "data.frame"
class(readd(tibble.data.by))
# [1] "tbl_df"     "tbl"        "data.frame"
```

tibble.data.by returns `[1] "tbl_df"     "tbl"        "data.frame"` but data.table.by returns `[1] "data.frame"` where I expected `[1] "data.table" "data.frame"`. Drake package version used was `[1] ‘7.8.0.9000’`

**Comment by wlandau** [comment]
Thanks for reporting this, glad I know about it now.

The issue seems to come from the fact that dynamic branching uses [`vctrs`](https://github.com/r-lib/vctrs) behind the scenes. In most cases, `vctrs` makes data types predictable and robust, and it makes data aggregation seamless. However, it does not seem to preserve the `data.table` class (though it does preserve `tibble`s).

``` r
library(data.table)
library(vctrs)
library(tibble)

# Original data.
d <- as.data.table(mtcars)
t <- as_tibble(mtcars)

# Original classes.
class(d)
#> [1] "data.table" "data.frame"
class(t)
#> [1] "tbl_df"     "tbl"        "data.frame"

# Aggregate with vctrs.
vd <- vec_c(d, d)
vt <- vec_c(t, t)

# Classes of the results.
class(vd)
#> [1] "data.frame"
class(vt)
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2019-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Looking at https://github.com/r-lib/vctrs/issues/694, I see that the maintainers of `vctrs` are already working on this issue. But regardless of how it turns out, `vctrs` just fit so well into dynamic branching that `drake` will continue to use it wholeheartedly.
