### ISSUE TITLE
About specifying objects outside of `drake_plan()`

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#1164]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

(Not an issue just a design discussion.)

Sometimes I specify objects outside of `drake_plan()`.
I usually do this when the objects should not become a target.
This helps me distinguishing random objects (which I usually create to group certain targets to be used within branching call) from targets.

**EDIT: Seems I was wrong and all objects within `drake_plan()` are becoming a target no matter if they are created with `target()` or not. The overall topic still applies :)**

However, this only works if those objects do not contain objects (e.g. a list of targets) but just character vectors (e.g. some names used as the grouping variable in a branching call).

Below is a small script to illustrate the issue better.

- I start with a section named "custom aggregations" which contains such character vectors.

- Other non-targets grouping objects such as `ps_rf_filter_rep` however have to live within `drake_plan()` to play nicely within the dependency pipeline (which makes sense).

Sometimes I come across the issue that I specify objects like `ps_rf_filter_rep` outside of `drake_plan()` as well and therefore get an error during `r_make()`.

However, I also see you creating certain objects outside of `drake_plan()` sometimes.
I am wondering if it would make sense to be more strict about this?
Maybe {drake} should check for objects created outside of `drake_plan()` if there is a `drake_plan()` call in an R script?

My reasoning for that is that having this differentiation between objects within `drake_plan()` and outside raises potential confusion to users, especially new ones.
Also it introduces the issue mentioned above of objects which contain targets to be unknown to {drake} if they are created outside of `drake_plan()`, even if they should not become a target.

```r
# Custom aggregations ----------------------------------------------------------

# The following three objects are for creating a pretty learner ID for the
# tune wrapper
learner_names = c(
  "RF MBO ",
  "XGBOOST MBO ",
  "SVM MBO "
  )

filter_names_pretty = c(
  "Car",
  "Info Gain",
  "Relief",
  "Pearson",
  "MRMR",
  "CMIM"
)

learner_ids_pretty = purrr::map(learner_names, ~ paste0(.x, filter_names_pretty)) %>%
  purrr::flatten_chr() %>%
  c(., sprintf("%sBorda", learner_names)) %>%
  c(., sprintf("%sPCA", learner_names)) %>%
  c(., sprintf("%s MBO", c("Lasso", "Ridge")))

# Plan -------------------------------------------------------------------------

tune_wrapper_plan <- drake_plan(

  # we need to create the repeated objects outside of `ps_mbo` to be
  # picked up correctly
  ps_rf_filter_rep = rep(list(ps_rf_filter), length(filter_names)),
  ps_rf_filter_xgboost = rep(list(ps_xgboost_filter), length(filter_names)),
  ps_rf_filter_svm = rep(list(ps_svm_filter), length(filter_names)),

  # order is important here! Follows the order of 'filter_wrappers_all'
  ps_mbo = c(
    # simple filters
    ps_rf_filter_rep,
    ps_rf_filter_xgboost,
    ps_rf_filter_svm,

    # Borda
    list(ps_rf_filter),
    list(ps_xgboost_filter),
    list(ps_svm_filter)
)

[...]
```

**Comment by wlandau** [comment]
By design, `drake` has always been sensitive to what goes on in your environment. I think that's a huge part of what makes it R-focused. (Other pipeline tools make you write scripts, which pulls us outside of the R and often obstructs our relationship with R.)

I think global objects are totally fine as long as you set up the R session in a consistent way before calling `make()`. Most projects that need `drake` are so computationally intensive that they are fully automated in batch mode anyway (as opposed to interactive console-only programming that is so common in the R community).

I do not have plans to disallow non-function global objects. But as you know, if session reproducibility could become a problem, I always recommend `r_make()`.

Some objects are necessary to the construction of the plan, e.g. tidy evaluation. Those objects are going to be there right before the call(s) to `drake_plan()`, and that's fine.

Another thing to think about is efficiency. How long does it take to compute those global objects? How big are they? If either is a concern, the global object should be a target so it does not have to rerun or get hashed every time you run the workflow.

**Comment by pat-s** [comment]
>  Most projects that need drake are so computationally intensive that they are fully automated in batch mode anyway (as opposed to interactive console-only programming that is so common in the R community).

Yeah, fully agree.

> Another thing to think about is efficiency. How long does it take to compute those global objects? How big are they? If either is a concern, the global object should be a target so it does not have to rerun or get hashed every time you run the workflow.

Yes, makes sense!
