### ISSUE TITLE
Determine nonstandard cache location from within make()

### ISSUE THREAD

**Issue by brendanf** [ropensci/drake#1167]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [ ] If you think your question has a quick and definite answer, consider posting to [Stack Overflow](https://stackoverflow.com) under the [`drake-r-package` tag](https://stackoverflow.com/tags/drake-r-package). (If you anticipate extended follow-up and discussion, you are already in the right place!)

## Question

Is there a way to determine from inside target code what the location of the drake cache used in the current make invocation is?

```r
library(drake)
cache2 <- new_cache(".cache2")
plan <- drake_plan(x = 1, y = readd(x))

make(plan, memory_strategy = "none", cache = cache2)
## target x
## target y
## fail y
## Error: Target `y` failed. Call `diagnose(y)` for details. Error message:
##  key 'x' ('objects') not found
```

Of course it can be passed explicitly from outside, but it would be nice to be able to specify "readd from whatever cache `make` is currently using".

**Comment by wlandau** [comment]
I would actually prefer to limit automatic cache detection. Searching for the default `.drake/` folder from `readd()` is usually fine because it is clear what `drake` is doing, but as soon as people start creating their own caches, we need to worry about situations where people create multiple caches side by side, to say nothing of alternative `storr` backends like `storr_dbi()`.

Even with the default `.drake` folder, it is dangerous to recurse upwards in `make()`. I regret this feature of `make()`, which is why I plan to remove it next time I have an excuse for a round of breaking changes, re #919. Related: https://github.com/ropensci/drake/blob/8004f4cd33b89e5034e28536ae2dd3e514f1bc1c/R/make.R#L570-L582

**Comment by brendanf** [comment]
If I understand correctly, then the only solution when using `make(memory_strategy = "none", cache = my_cache)` is to explicitly code it into every `readd` in the plan?

```
library(drake)
plan <- drake_plan(x = 1, y = readd(x, cache = ignore(my_cache)))

my_cache <- new_cache(".my_cache")
make(plan, memory_strategy = "none", cache = my_cache)
```

**Comment by wlandau** [comment]
Or wrap `readd()` in your own function.

```r
my_cache <- new_cache(".my_cache")
rdd <- function(...) readd(..., cache = my_cache)
```

NB the latest `drake` should now automatically `ignore()` caches.
