### ISSUE TITLE
[Dynamic branching] Harmonizing notation when mapping over lists / vectors?

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#1170]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

I am using dynamic branching since a week now.
I found myself often in the situation outlined below

```r
my_list = list(
  foo1, foo2
)

my_vec = c(
  vec1, vec2
)

target(
  function(
    arg1 = my_list[[1]], # when using lists one needs [[1]] in dyn. br.
    arg2 = my_vec
  ),
  dynamic = map(my_list, my_vec)
)
```

Due to the behavior of `vctrs` behind the scenes, a list used in dynamic branching needs to be subsetted first to iterate over such in a vector like fashion.

From a users perspective I would find it more natural and understandable if both vectors and lists would behave in the same way -> without the `[[1]]` requirement.

Would it make sense to do the subsetting of lists used as a dynamic varible in dynamic branching internally so that one could write

```r
target(
  function(
    arg1 = my_list, # removing the [[1]] req for lists
    arg2 = my_vec
  ),
  dynamic = map(my_list, my_vec)
)
```

---

In static branching one can also iterate over lists without the `[[1]]` so it would make things more consistent in this case also?

Maybe I am overlooking something that would not be possible anymore with lists in dynamic branching when doing this behind the scenes?

**Comment by wlandau** [comment]
This comes up a lot (e.g. https://github.com/ropensci/drake/issues/1087#issuecomment-563656956). I realize `[[1]]` feels annoying and out of place, but this behavior is not going to change in the foreseeable future. Reasons:

# Breaking change

Current code with `[[1]]` would no longer work if `drake` took special measures to adjust for it

# Internal consistency *within* dynamic branching

Going all-in on `vctrs` seems much better than an awkward hybrid born out of reactions to edge cases. That way, there is no ambiguity. The `vctrs` standard is comprehensive, internally consistent, elegant, and well-documented, and it stands on its own super well. Users can read https://vctrs.r-lib.org/ to understand it, and they can call `vec_slice()` and `vec_c()` to know exactly what values they will get from `drake`. Plus, `vctrs` and its standard are maintained by Hadley, who I trust to this task far more than I trust myself.

# Paternalistic nudge away from list targets

The extra friction for lists is actually a good thing. It is [opinionated](https://peerj.com/preprints/3210/), and it is a strong [nudge](https://en.wikipedia.org/wiki/Nudge_(book)). I want users to [think harder about the data structures of their targets](https://books.ropensci.org/drake/plans.html#how-to-choose-good-targets). In stats and data science, anything that can be a data frame *should* be a data frame (At least that's my strong opinion.) The Tidyverse, `data.table`, and the database workflows that came before have shown us just how powerful data-frame-centric workflows can be. And in `drake`, data frames open up [fast target formats](https://books.ropensci.org/drake/plans.html#special-data-formats-for-targets), and they unlock the [full magic of automatic sub-target aggregation in dynamic branching](https://books.ropensci.org/drake/dynamic.html#dynamic-targets).

# Static vs dynamic branching

I am not so sure there is discord between static and dynamic branching on the issue of `[[1]]` because the two systems work on fundamentally different principles. Static branching is about metaprogramming. The input is a bunch of symbols, and the output is more code (in the form of a `drake` plan). Dynamic branching is about the actual data, and the end product is data.

**Comment by wlandau** [comment]
cc @kendonB

**Comment by wlandau** [comment]
Another thing to consider: Dynamic branching may appear to use `[[1]]` for vectors at first glance, but that assumption is quickly dispelled once you use `group(..., .by = ...)`. In group() with .by, sub-targets are true multi-element slices, not single elements. This is another area where complete trust in `vctrs` is so powerful. Suddenly, we get dplyr-like group_by() behavior for free, without needing to change the underlying principles of dynamic branching.
