### ISSUE TITLE
Sponsoring the project?

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#1231]
Hi Will,

I would like to sponsor drake because it is so valuable for my work.
Any plans on activating GitHub sponsors for the repo (or your account)?

**Comment by wlandau** [comment]
Thanks so much for the idea, Pat. I am so glad `drake` turned out to be so valuable.

In my current job situation, however, I cannot legally or ethically earn an income from this project. (Even if I were to leave, I would need to check because my employer has copyright and they have given me time to work on it. I know for certain that I would be prohibited from collecting royalties on https://books.ropensci.org/drake/ if it were to be published in print form.) My industry has tight restrictions that academics do not always realize.

But rest assured, I am still committed. Although there are no groundbreaking new features coming up in the near future, I have grand plans to not only refactor `drake`'s code base to make it cleaner and more trustworthy, but also level up my game as a developer with `drake` in mind.

Urgent projects at my day job are on fire at the moment, but I will not let that stop me from fixing critical bugs, publishing to CRAN regularly, and helping users when I can. And if something happens to me, I trust rOpenSci as a safety net for the package.

**Comment by pat-s** [comment]
Thanks for the openness!

I was not fearing any lack of support/features now or in the near future - just wanted to show my appreciation :)

> Urgent projects at my day job are on fire at the moment, 

Good luck! I am very certain that you'll 🚀 them
