### ISSUE TITLE
New visualization does not work properly for large plans

### ISSUE THREAD

**Issue by Plebejer** [ropensci/drake#1303]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] I am reasonably sure this is a genuine bug in `drake` and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)
- [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

Between version 7.12.0 and 7.12.4 `r_vis_drake_graph()` got updated and now uses fancy "curly" arrows to connect targets. But this seems to produce unreadable visualizations for large plans. Here are the dependency graphs from version

### 7.12.0:
![image](https://user-images.githubusercontent.com/6517388/89664019-ca7cd100-d8d6-11ea-8fe2-52702f87d398.png)

### 7.12.4:
![image](https://user-images.githubusercontent.com/6517388/89664150-0021ba00-d8d7-11ea-9229-ef03efd4911b.png)

## Reproducible example

I'll try to provide a reprex next week.

## Expected result

The dependency graph should be spaced such that it is (somwhat) readable (I know it's hard with plans of this size).

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(si = TRUE)`) and include the output.

**Comment by wlandau** [comment]
Yeah, I do realize the new graph layout is a bit of an adjustment. This is actually `visNetwork`'s default behavior, it does not set a 1:1 aspect ratio on its own. In previous versions of `drake`, I was able to [hack the graph to force a 1:1 aspect ratio](https://github.com/ropensci/drake/blob/0ea2998ce8d2bbb822cf5a78d2466e67e18da997/R/vis_drake_graph.R#L298-L299), but since we started using `visHierarchicalLayout()` again in #1289, this became impossible. Nothing I can do except maybe revert #1289, which does not seem worth it.

For what it's worth, the hack did comes with a downside. If you force a 1:1 aspect ratio, vertices pile on top of each other and it is impossible to see target names. Without the hack, zooming in interactively still gives a clear picture.

In general, these large graphs are still going to be hard to read. I suggest you consider switching to dynamic branching so the number of nodes in the graph goes down. Dynamic branching also helps with performance. Initialization times for `make()` and `vis_drake_graph()` go way down.

**Comment by wlandau** [comment]
But maybe `visNetwork` itself has a workaround. I will ask.

**Comment by wlandau** [comment]
I may revisit this issue, depending on https://github.com/datastorm-open/visNetwork/issues/386.

**Comment by mstr3336** [comment]
IF you're interested in a userland workaround, you can always post-process the graphs put out by `drake`, using `visNetwork` to suit your dataset. 

It'll resemble something like 

```r
# I chose 2500 since the value given in #1289 is 250, and I guess 10 times that might be okay for you?
my_level_separation = 2500 

my_graph %>% visNetwork::visHierachicalLayout(levelSeparation = my_level_separation)
```

`drake`'s defaults for these spacings likely do a better job servicing more usecases than something that would work for yours. 

A reasonable value for level separation is probably calculable based on some ratio of `n_nodes` / `n_levels` multipled by some constant (`n_levels` being the number of stages from the leftmost node to the rightmost)

**Comment by robitalec** [comment]
Thanks @matthewstrasiotto - that just turned my visGraph from:

![image](https://user-images.githubusercontent.com/16324625/99579117-52837400-29b8-11eb-95fc-4a563413ee6b.png)


to:

![image](https://user-images.githubusercontent.com/16324625/99579063-41d2fe00-29b8-11eb-983a-19264ae28463.png)


(Small note: typo in your code chunk, missing an "r")

```r
my_graph %>% visNetwork::visHierarchicalLayout(levelSeparation = my_level_separation)
```

**Comment by matthiasgomolka** [comment]
@matthewstrasiotto, @robitalec, thanks, this is super helpful! I added `direction = "LR"` to the `visNetwork::visHierarchicalLayout` call to get the usual drake graph direction from left to right.

**Comment by matthewstrasiotto** [comment]
It might be worth reopening this issue to either include an override in the params, or to find a way to tell drake to calculate a more appropriate separation

**Comment by wlandau** [comment]
Added a `level_separation` argument to `vis_drake_graph()` and `render_drake_graph()` in https://github.com/ropensci/drake/commit/65bc865153097b4f9455172327e999e436d30a63.
