### ISSUE TITLE
Hash not found when repository is cloned to another directory

### ISSUE THREAD

**Issue by jrosen48** [ropensci/drake#1319]
## Prework

- [ x ] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [ x ] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [ x ] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.
- [ x ] If you think your issue has a quick and definite solution, consider posting to [Stack Overflow](https://stackoverflow.com) under the [`drake-r-package` tag](https://stackoverflow.com/tags/drake-r-package). (If you anticipate extended follow-up and discussion, you are already in the right place!)

## Description

When I run {drake} locally on the machine that I used to write and run my analysis up to this point, it runs flawlessly. However, when someone clones the project from GitHub to their machine runs (or when I clone the repository to another directory and then) `drake::r_make()`, I get this error: 

```{r}
 x hash 'bd4bfbac8c5fcdfc' not found 
```

There is one Stack Overflow question on a similar/the same issue [here](https://stackoverflow.com/questions/58070874/hash-not-found-while-visualizing). It seems that the issue may be due to the version of {drake}, rather than visualizing the plan. I updated my version of {drake}, ran `drake::clean()`, and also deactivated {renv}, but neither seemed to do the trick. 

I also tried to comment out the line of code in `_drake.R` for the visualization, but, then, the error trace seemed to then have to do with the next line, `drake_config()`.

## Reproducible example

The repository is here, but it depends upon a privately-shared `.rda` file (which I'm happy to share if it assists debugging): https://github.com/jrosen48/ngsschat-sentiment

## Desired result

I'd like {drake} to be able to run my analysis beyond the directory I created it in!

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(si = TRUE)`) and include the output.

```{r}
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] pillar_1.4.6      compiler_4.0.2    dbplyr_1.4.4      prettyunits_1.1.1 progress_1.2.2    tools_4.0.2      
 [7] digest_0.6.25     packrat_0.5.0     lifecycle_0.2.0   tibble_3.0.3      lattice_0.20-41   pkgconfig_2.0.3  
[13] rlang_0.4.7       Matrix_1.2-18     igraph_1.2.5      DBI_1.1.0         cli_2.0.2         rstudioapi_0.11  
[19] filelock_1.0.2    yaml_2.2.1        parallel_4.0.2    xfun_0.16         dplyr_1.0.2       storr_1.2.1      
[25] knitr_1.29        hms_0.5.3         generics_0.0.2    vctrs_0.3.4       fs_1.5.0          grid_4.0.2       
[31] tidyselect_1.1.0  glue_1.4.2        drake_7.12.5      R6_2.4.1          fansi_0.4.1       base64url_1.4    
[37] txtq_0.2.3        purrr_0.3.4       blob_1.2.1        magrittr_1.5      backports_1.1.9   ellipsis_0.3.1   
[43] htmltools_0.5.0   usethis_1.6.1     assertthat_0.2.1  renv_0.11.0       crayon_1.3.4     
```

**Comment by wlandau** [comment]
Unfortunately, `drake` caches are not very portable. Because of the way [`storr`](https://github.com/richfitz/storr) works, they're just not going to do well on GitHub. I recommend you omit `.drake` from Git commits. Maybe a service like Dropbox or Google Drive would allow you to share caches more easily, but even then it takes a long time to upload all those tiny files. I cannot fix this without a large number of tedious and painful breaking changes, and it is one of the major reasons why I created  [`targets`](https://github.com/wlandau/targets).

I can reproduce your error with `drake::drake_cache()` after cloning the repo. (Thanks for setting that up and making it easy for me to reproduce!) The error in this particular case happened because [this key file](https://github.com/jrosen48/ngsschat-sentiment/blob/master/.drake/keys/session/drake_version) refers to a data file that should be at `.drake/data/bd4bfbac8c5fcdfc.rds` but is missing. It looks like you omitted all of `.drake/data/` from GitHub but committed other files in the cache. That's what is confusing `drake`. With cache files, it's all or nothing. Users must either keep all of `.drake/` or none of it. (Not so in [`targets`](https://github.com/wlandau/targets), which only requires that the `_targets/meta/meta` data table file remain uncorrupted).

**Comment by jrosen48** [comment]
Thanks so much! Makes sense. @datalorax just made me aware of {targets} in the context of our collaborative project - planning to switch over for this (later) or our next project!
