### ISSUE TITLE
using .RData files as input

### ISSUE THREAD

**Issue by TrevMat** [ropensci/drake#1320]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] If you think your question has a quick and definite answer, consider posting to [Stack Overflow](https://stackoverflow.com) under the [`drake-r-package` tag](https://stackoverflow.com/tags/drake-r-package). (If you anticipate extended follow-up and discussion, you are already in the right place!)
- [x] If you identify problems, be considerate of the maintainer's time and make it as easy as possible to troubleshoot them. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Question

I have a project which depends on health data.  A requirement of using this data is that it must be de-identified before being moved to Uni.  I've done this in RStudio at my workplace and then saved the resultant dataframe into a .RData file, and am now processing it at Uni as part of my PhD.  Eventually I will need to use the uni's high performance cluster so I can't do either part of the analysis at the other place (if that makes sense!)

I'm now trying to use drake (for the first time) and have struck an issue with loading the .RData files.  I wish to be able to make each of the tibbles (stored individually in separate .RData files - one tibble will change in time when I get updated data, but the others *shouldn't* change).

load returns the names of the objects found in the datafile, so the target becomes a character string (single tibble to each .RData file) and that gets passed to the next function which I should be processing the tibble's rows.  In the reprex below, both Dispatches.pl and SA1Data are the names of tibbles with simple feature data which I'd prefer to keep as tibbles to preserve the structure and attribute information rather than re-processing in this project (and possibly others.)

How do I track the status of the file, load the resultant data frame and refer to it in the subsequent function call(s)?

## Reproducible example

```R
the_plan <-
  drake_plan(

   ## Plan targets in here.
    dispatchData = load(file_in("Source Data/StudyDispatches.RData")),
    SA1Data      = load(file_in("Source Data/sa1.processed.SEIFA.RData")),
    HospitalLocs = read.csv(file_in("Source Data/hospitals.csv")),
    
    TravelSpeedData = createSpeedDataset(dispatchData, SA1Data, HospitalLocs)
)
```

>readd("dispatchData")
[1] "Dispatches.pl"    

>readd("SA1Data")
[1] "sa1Joined"

>make(the_plan)
x fail TravelSpeedData
Error: target TravelSpeedData failed.
diagnose(TravelSpeedData)$error$message:
  no applicable method for 'st_transform' applied to an object of class "character"
diagnose(TravelSpeedData)$error$calls:
  global::createSpeedDataset(dispatchData, SA1Data, HospitalLocs)
  sa1Joined %>% st_transform(crs = cPl_crs)
  base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  base::eval(quote(`_fseq`(`_lhs`)), env, env)
  base::eval(quote(`_fseq`(`_lhs`)), env, env)
  `_fseq`(`_lhs`)
  magrittr::freduce(value, `_function_list`)
  base::withVisible(function_list[[k]](value))
  function_list[[k]](value)
  sf::st_transform(., crs = cPl_crs)

If you identify problems, be considerate of the maintainer's time and make it as easy as possible to troubleshoot them. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

**Comment by wlandau** [comment]
If you need serialized R files, I recommend that you use RDS and not `RData`. When you `load()` an RData file, it produces a bunch of side effects in the calling environment instead of returning a meaningful value. That's what is confusing `drake`. `drake` assumes each target is a data object returned from the corresponding command in the plan.

If `RData` is unavoidable, I recommend you write helper functions to wrap up the relevant data and return it as a data object from the target. Then, `drake` will automatically store it in an RDS file in `.drake/data/` which you can then load with `drake::loadd()` or `drake::readd()`. And if RDS is inefficient, you can choose one of [these more efficient formats](https://books.ropensci.org/drake/plans.html#special-data-formats-for-targets).

Sketch:

```{r}
load_rdata <- function(rdata_file) {
  envir <- new.env(parent = emptyenv()) # Define an empty environment to control the data.
  load(rdata_file, envir = envir) # Control the data and avoid transient side effects.
  as.list(envir) # Return a list with all the data objects in the RData file.
}

plan <- drake_plan(
    dispatchData = load_rdata(file_in("Source Data/StudyDispatches.RData")),
    SA1Data = load_rdata(file_in("Source Data/sa1.processed.SEIFA.RData")),
    HospitalLocs = read.csv(file_in("Source Data/hospitals.csv")),
    TravelSpeedData = createSpeedDataset(dispatchData, SA1Data, HospitalLocs)
)
```

`drake` runs [static code analysis](https://adv-r.hadley.nz/expressions.html#ast-funs) on the commands and functions in order to infer dependency relationships. For example, `TravelSpeedData` depends on `SA1Data` because the symbol `SA1Data` is mentioned in the command for `TravelSpeedData`.

```{r}
vis_drake_graph(plan)
```

![Screen Shot 2020-09-09 at 10 12 59 PM](https://user-images.githubusercontent.com/1580860/92673676-a81d0f80-f2e9-11ea-9d89-ab9f73d81e20.png)
