### ISSUE TITLE
Mention targets package in README?

### ISSUE THREAD

**Issue by joelnitta** [ropensci/drake#1332]
## Prework

* [X] Read and agree to the [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/drake/blob/master/CONTRIBUTING.md).
* [X] If there is [already a relevant issue](https://github.com/ropensci/drake/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

I just came across the [`targets` package](https://wlandau.github.io/targets/), and it looks great. However, it's not clear to me when I would need to stick to `drake`, and when I should use `targets`. Can this be addressed in the README? At the least, I think `targets` should be mentioned in the README (and probably the manual too) so users know that it is an option they should check out before committing to `drake`.

**Comment by wlandau** [comment]
I agree we should do this, but I would prefer to wait until [`targets`](https://github.com/wlandau/targets) and [`tarchetypes`](https://github.com/wlandau/tarchetypes) are part of rOpenSci and released to CRAN. (rOpenSci review just started: https://github.com/ropensci/software-review/issues/401.)

[`targets`](https://github.com/wlandau/targets) compares itself to `drake` in order to justify its existence, so there is detailed documentation at https://wlandau.github.io/targets/articles/need.html#drake and https://wlandau.github.io/targets-manual/index.html#what-about-drake. Briefly:

1. `drake` is never going away.
1. `targets` was necessary in order to [surpass the permanent limitations of `drake`](https://wlandau.github.io/targets/articles/need.html#drake).
1. If you know `drake`, you [already almost know `targets`](https://wlandau.github.io/targets-manual/index.html#what-about-drake).
