### ISSUE TITLE
drake::r_vis_drake_graph(targets_only = TRUE) gives bad layout

### ISSUE THREAD

**Issue by feinmann** [ropensci/drake#1356]
Hi there,

I am drawing my plan using `drake::r_vis_drake_graph(targets_only = TRUE)` which functions as expected without the parameter `targets_only = TRUE`, but as given, the result is poorly layouted, without space between the nodes. 

![image](https://user-images.githubusercontent.com/2109648/107045494-daae3400-67c5-11eb-9f25-3e0a51369dd0.png)

Sorry, I cannot provide a reprex at the moment. So I am just wondering, am I missing an obvious setting, or is there a possibility to force a certain layout? Otherwise I suspect that I somehow screwed up my setup.

Thanks for any hints.

**Comment by wlandau** [comment]
Unfortunately, we have little control over the layout because it is managed internally by the `visNetwork` HTML widget. The `visNetwork` R package may allow you to adjust some things yourself using the output of `r_vis_drake_graph()`. There is also some discussion at https://github.com/ropensci/drake/issues/1303 about level separation, which you can now directly set in the graphing functions.
