### ISSUE TITLE
Trouble with caches sent through Dropbox

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#198]
Never seen it before.
```
cache pathto/.drake
connect 61 imports: ...
connect 200 targets: ...
Error in rawToChar(as.raw(x)) : 
  embedded nul in string: 'initial_drake_version\0\0\x9a\x9d\xdc\0J\xe9\0\0\0(\x9d\xf9brם\0\xca)\0\0\xb4\xd7\0\0\0\0\xb9'
In addition: Warning message:
In rawToChar(as.raw(x)) :
  out-of-range values treated as 0 in coercion to raw
```

**Comment by wlandau** [comment]
Weird, I have no idea. Where exactly does it happen? Can you reproduce it with code you can share?

**Comment by wlandau** [comment]
But on a case by case basis, you may be able to fix your project with this:

```r
cache <- get_cache()
cache$clear(namespace = "session")
cache$gc()
```

**Comment by wlandau** [comment]
So I looked into the `storr` internals, and I [this](https://github.com/richfitz/storr/blob/a0183fe1b9b921b319b3e79c2bde19203dca82ff/R/base64.R#L72) is the last thing that runs before the error. It looks like `drake` is trying to read a base 64-encoded key and it fails. I still do not know the answer, but maybe it has something to do with a mangled filename. Is this the same project you are storing on Dropbox from #197?

**Comment by kendonB** [comment]
It is the same project from #197, but only one user is writing to the project.

**Comment by kendonB** [comment]
Still get the error when we run this:

```
cache$clear(namespace = "session")
Error in rawToChar(as.raw(x)) :
 embedded nul in string: 'initial_drake_version\0\0\x9a\x9d\xdc\0J\xe9\0\0\0(\x9d\xf9brם\0\xca)\0\0\xb4\xd7\0\0\0\0\xb9'
In addition: Warning message:
In rawToChar(as.raw(x)) :
 out-of-range values treated as 0 in coercion to raw
```

**Comment by wlandau** [comment]
You may have to cache$gc() to remove the files. Alternatively, you could try to overwrite them with

```r
cache$set(
  key = "sessionInfo",
  value = sessionInfo(),
  namespace = "session"
)
```

The fact that it's the same project from #197 makes me think a file might have been corrupted during the transfer.

**Comment by kendonB** [comment]
We just burned it down and started over.

**Comment by wlandau** [comment]
Sorry to hear it came to that. Please let me know if it happens again. You might also want to post an issue to the `storr` page. @richfitz might like to know.

**Comment by richfitz** [comment]
This is _possibly_ due to changes in R's serialisation format (in the last version they introduced a new serialisation format and immediately made it the default.  The version of storr up from just before Christmas (1.1.3) locks the serialisation format to version 2).

But that seems unlikely given where the link to the storr internals goes.  That suggests that the other junk (`\0\0\x9a\x9d\xdc\0J\xe9\0\0\0(\x9d\xf9brם\0\xca)\0\0\xb4\xd7\0\0\0\0\xb9`) was written onto the character string that represents a key after the bit of obvious text there.  Those don't look like the beginning of R's serialisation signatures, or anything really.

Do you have a copy of the archive that you can share?  That suggests that there is some filename with a very weird name.  It would be interesting to see if anything looks odd in the directory, because rds storrs just work with filenames

**Comment by kendonB** [comment]
Sorry, we completely got rid of the corrupted archive and started again. I also won't be able to share the archive as it contains some proprietary data. 

If it happens again, we can go back and forth debugging again.

**Comment by richfitz** [comment]
That's OK - if it happens again I don't need the archive, but look to see if there are any unusual filenames.  I've not seen this with a lot of storr use, and can't see an obvious way that would have happened from R (R _really_ dislikes strings with embedded nulls and so it's not clear how it could have written to a file with one).

It's quite possible that there was a problem with the encoding/decoding of filenames but that's also been pretty heavily tested now.  I should probably resolve https://github.com/richfitz/storr/issues/44 but that's complicated with the retaining padding...

**Comment by kendonB** [comment]
I ran into the problem again. Two things might be going on:

Dropbox itself is introducing some temporary files that it uses to make itself run

OR the ``storr`` is somehow getting messed up by me ``readd``ing while my colleague is ``make``ing.

**Comment by richfitz** [comment]
Did you keep a copy around this time that can be used for trying to root out the cause?

Based on what @wlandau posted before this looks like the filename of the key is corrupted.  I don't have a copy of the names of the keys to work with so at a complete guess:

```r
str <- storr::encode64("hello")
storr::decode64(paste(str, "(conflicted copy)"))
# Error in rawToChar(as.raw(x)) : 
#   embedded nul in string: 'hello\0\0\0(\x9d\xf9brם\0\xca)'
# In addition: Warning message:
# In rawToChar(as.raw(x)) :
#   out-of-range values treated as 0 in coercion to raw
```

so that looks similar to what you're seeing (though I'm surprised that `initial_drake_version` is in cleartext for a string that is being run through decode64 - any thoughts there @wlandau?). Above, I am trying to remember what dropbox does when it messes up files - I use it as little as possible because I would not trust it with any data I cared about.  It's a regular source of file corruption for research projects so far as I can see.

So, continuing guessing, options here are:

1. there have been either two conflicting writes that have occurred between dropbox syncs
2. dropbox has become confused about which copy of a file is current, even with just one write (perhaps timestamps have confused it...)

(I don't think that reading alone should be causing a problem, but I have no idea how file locking might impact on how dropbox decides to do things, if at all)

I saw similar behaviour to this with a student's git repo on onedrive - dropbox seems to have added some secret sauce to prevent git corruption, but it did used to be an issue.  The problem is that dropbox is not really a filesystem and they expect people to notice that their word documents etc have these conflicted copy names and resolve them.

The solution, if you want to use dropbox for this sort of thing, is probably to go into the keys folder, find the conflicted copy files, manually resolve them and then things will just work.  That's what dropbox wants you to do!

I'm not sure how drake exposes storr, but if you can get the storr object as `st` then:

```r
dir(st$driver$path, recursive = TRUE, pattern = "conflict", ignore.case = TRUE)
```

may give an indication of how widespread this sort of thing is.

We use storr in our HPC system at work with hundreds of processes on different machines simultaneously reading and writing - it's designed to be fairly robust to simultaneous access (in particular the _data_ part should be immune to this).  But we have nfs and smb filesystems that seem deal with this much better.  The problem dropbox tries to solve is much more complicated.

Hope that helps!

**Comment by wlandau** [comment]
@richfitz I really appreciate the troubleshooting. Now that you mention it, I am just as surprised as you are to see `initial_drake_version` mixed in as cleartext. I am using `storr`'s intended API to [store the `initial_drake_version`](https://github.com/ropensci/drake/blob/5f54d35717f65c2f801658c9bfc8e7a620bfff59/R/cache.R#L394), so it is hard to imagine what could be different.

@kendonB Do you know the exact line in `drake`'s code base where the error occurs? Also, I wonder what would happen if you tried a [custom cache](https://ropensci.github.io/drake/articles/storage.html) that does not mangle the key:

```r
make(
  your_plan,
  cache = storr::storr_rds(".drake", mangle_key = FALSE), # default in storr
  ...
)
```

This may not necessarily solve the problem, but at least you will have human-readable keys and troubleshooting may be easier. In its default cache, `drake` mangles the keys to make sure they are all legal file names. For example, some workflows have `'nested/file/targets.txt'`.

Reopening again. I doubt the problem is in `drake` itself, but the solution is important for `drake`'s usability. I will close again if it becomes solved or we can no longer reproduce it.

By the way, I am at the RStudio Conference from now through Saturday, and I will not have as much time  as usual this week.

**Comment by kendonB** [comment]
thanks heaps for the help. If it is simply conflicted copies causing the problems, I'm guessing that the following might solve it. (We again simply made from scratch.) @wlandau please confirm that this would be safe.
```r
list.files(".drake", recursive = TRUE) %>% 
  stringr::str_subset("conflicted copy") %>% 
  file.remove()
```

**Comment by wlandau** [comment]
`Drake` does not write any files named `"conflicted copy"`, so that should be fine.

**Comment by richfitz** [comment]
Actually @wlandau - the clearttext drake bit is fine - I can see a similar one above in my example too:

```
embedded nul in string: 'hello\0\0\0(\x9d\xf9brם\0\xca)'
```

this is what I get for trying to debug things on the train...

I'd wager any amount of money it's just conflicted copy.  Next time it happens (and it _will_ happen) can you please post the output of

```r
dir(".drake", recursive = TRUE, pattern = "conflict", ignore.case = TRUE)
```

so I can get a sense of how dropbox messes things up.  It's possible I can pop a repair function into storr that implements a couple of heuristics (e.g., take most recent/latest/nonconflicted etc) if I can understand how the different broken files are being created.  All you will be disclosing is the name of the keys

**Comment by kendonB** [comment]
Superb. I will send the output of ``dir(...)`` _when_ it happens again.

**Comment by richfitz** [comment]
Thanks :)

At some point something will replace dropbox for this sort of sharing.  It's thoroughly depressing that there is not a better solution yet.

**Comment by wlandau** [comment]
Thanks, @kendonB. Will reopen when the next error happens and we can work on the files.

**Comment by kendonB** [comment]
Indeed, Dropbox's conflicted copies:

[1] "keys/config/aG9vaw (Sandy Sum's conflicted copy 2018-01-31)"                                                                                                                                                      
[2] "keys/config/am9icw (Sandy Sum's conflicted copy 2018-01-31)"                                                                                                                                                      
[3] "keys/config/c2VlZA (Sandy Sum's conflicted copy 2018-01-31)" 

There are heaps of them and they are in meta, config, session, objects

**Comment by kendonB** [comment]
Also, I was wrong that it was just a single computer. My colleague was making on both her home and work computer.

**Comment by richfitz** [comment]
Could you please run this to show what is going on around any of those files and their conflicted friends:

```
file.info(dir("keys/config", pattern = "aG9vaw", full.names = TRUE))
```

**Comment by kendonB** [comment]
Gah we patched it again by deleting the conflicted copies. Will do so next time.

**Comment by wlandau** [comment]
We should probably include a note in the [caution vignette](https://github.com/ropensci/drake/blob/master/vignettes/caution.Rmd) on this. Seems like such a common use case.

**Comment by wlandau** [comment]
Update: if non-custom `drake` caches get corrupted when you upload them to Google Drive or Dropbox or the like, you can try to fix the problem with `drake_gc()` (development `drake` only). Related:

- [The issue explained](https://github.com/ropensci/drake/blob/master/vignettes/caution.Rmd#projects-hosted-on-dropbox-and-similar-platforms)
- https://github.com/ropensci/drake/issues/322
- https://github.com/richfitz/storr/issues/55
