### ISSUE TITLE
get file targets working in evaluate_plan

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#205]
the output for the target is currently:  ``'target_name.pdf'_replacement_value``

I would expect ``'target_name_replacement_value.pdf''``

hth

**Comment by wlandau** [comment]
Good question. Closing because I think I addressed this in #106. Let's follow up on that thread if you have ideas for a better interface.

Incidentally, I am starting an exciting collaboration with @krlmlr, and the interface will change a lot in the future. Eventually, the [recommended workaround](https://ropensci.github.io/drake/articles/caution.html#beware-unparsable-symbols-in-your-workflow-plan-) may no longer be needed.

**Comment by kendonB** [comment]
Oh superb! I hadn't seen that workaround. I look forward to testing out any
interface changes as well.
