### ISSUE TITLE
Make Workflow is circular error more useful

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#215]
It would be great if the above error identified the targets that are in conflict.

All I currently see is:

```
Error in build_drake_graph(plan = plan, targets = targets, envir = envir,  :
  Workflow is circular (chicken and egg dilemma).
```

**Comment by wlandau** [comment]
That is because [`drake` uses `igraph::is_dag()`](https://github.com/ropensci/drake/blob/51da28f748d12e4caf133f1d72571183ba2e05bb/R/graph.R#L91) to check for circularity (and I am starting to think this belongs in [`check_drake_config()`](https://github.com/ropensci/drake/blob/51da28f748d12e4caf133f1d72571183ba2e05bb/R/check.R#L48)). `is_dag()` checks for circularity, but unfortunately, it does not return any cycles. 

All we need is to detect one directed cycle. Any one will do. However, I am not sure it will be easy. There has been a lot of discussion on this as it relates to `igraph`, and @gaborcsardi has thought a lot about it,  but I do not know if `igraph` has this capability yet.

**Comment by wlandau** [comment]
Thanks to @gaborcsardi for telling me about `components(graph, mode = "strong")`. The strongly connected components should give us the cycles, which we can use to make the error messages more informative.
