### ISSUE TITLE
Job monitoring in viewer pane

### ISSUE THREAD

**Issue by dapperjapper** [ropensci/drake#254]
I don't know a lot about the job managing aspects of drake's back-end, but one of the reasons I love Makefile parallelism is that it I can see each job from `htop` in the terminal, how much resources each one is using, and kill any target individually without affecting my main R session. I often need to kill targets when I am iterating my code and realize I introduced a bug.

I've noticed some R packages and RStudio Addins using the viewer pane and Shiny to create interfaces to interact with content -- ex. the interactive network graph that Drake uses. 

Would it be possible to create some sort of webpage that pops up in the viewer pane, and that provides similar features to Makefile+htop but for any flavor of parallelism? Things that could be included:

- Target CPU & memory
- Kill target
- Previous build time vs current run time
- Targets built vs outdated targets

It seems like calls to `make()` would have to be non-blocking for the current R session for this to work, and there would have to be some way for running jobs to communicate with the page in the viewer pane.

I understand this is a *very* complex feature to build, but it is something I think would make Drake much more usable to a broader population of researchers.

**Comment by wlandau** [comment]
I have been dreaming about this for several months, and I would love to have it. However, because of the huge scope, I think it should be its own separate package. The code base of `drake` is already bigger than I would like it to be. In fact, as visualization in general gets more ambitious, I may even want to offload the graph plotting to a separate `drakevis` package. If you decide to start work on target monitoring, please let me know and I will follow and support it as much as my time allows.
