### ISSUE TITLE
Use read_drake_plan() as default value for "plan" argument?

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#261]
The current default `drake_plan()` seems rather useless in most cases.

Related: Memoizing multiple plans (by giving them names), or maybe even as first-class targets?

**Comment by wlandau** [comment]
Rather, I meant to say that I am totally behind using `read_drake_plan()` instead of `drake_plan()` as the standard default for `plan` arguments. Not sure about memoization, though. For workflow plans and targets, unless I am missing something here, it seems like active bindings and the current cache could probably accomplish the same thing.
