### ISSUE TITLE
Error in make() if drake was not attached when running the plan the first time

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#300]
Use case: Defining the workflow in a package-like setting using `pkgload::load_all()` .

``` r
plan <- drake::drake_plan(a = 1)
drake::make(plan)
#> cache /tmp/Rtmp2nnvQN/.drake
#> connect 1 import: plan
#> connect 1 target: a
#> check 1 item: a
#> target a
drake::make(plan)
#> cache /tmp/Rtmp2nnvQN/.drake
#> Warning in is.na(a): is.na() applied to non-(list or vector) of type 'NULL'
#> Error in if (is.na(a)) return(-1L): argument is of length zero
```

> Created on 2018-03-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wlandau** [comment]
This is because of how `drake` checks existing caches for compatibility with your current version of `drake`. The error happened when `drake` dug into the cached session info (from `drake_session()`), could not find the version of `drake` that created the cache, returned `NULL`, and compared it using the minimum compatible version using `compareVersion()`. `Drake` could not find the version number because it was looking among the attached packages only. Factoring in packages that were loaded but not attached seems to have fixed the problem.

**Comment by krlmlr** [comment]
Awesome, thanks for the quick fix!
