### ISSUE TITLE
Option to set a non default cache

### ISSUE THREAD

**Issue by bart1** [ropensci/drake#381]
I regularly work on a cluster where alternative locations for the drake cache are desirable based on the hardware set up. To each drake function call I now need to add `cache=cacheObj`. I think it would be a great feature to add the possiblity to set the cache once per session through a option call, something like `options(drakeDefaultCache=cacheObj)`. I do not have a complete overview of the package but is seems easy to implement through adjusting the `get_cache` function. If that is indeed the case, and the feature is desirable, I can make a pull request. Alternative an environmental variable can be used

**Comment by wlandau** [comment]
Interesting idea, I will think about it. It is unlikely that I will implement this, however, because reliance on options does not always bode well for reproducibility. The treatment of reproducible random numbers is a similar case. (See where the `make()` help file describes the `seed` argument.) @krlmlr convinced me that we should ignore the seed in the user's session (even seeds set by `set.seed()`) and force a seed of 0 if the user does not explicitly supply one to `make()` or `drake_config()`. That way, we avoid surprises. I think we should treat the `cache` argument the same way, but I will give the alternative some thought.

**Comment by bart1** [comment]
I see your concern, I was mostly looking for a way to reduce the verbosity of my code. Especially while debugging with functions like `diagnose`each time adding the `cache` arguments is a bit frustrating. I guess an alternative would be linking the `.drake` directory but I would not know how that would affect performance and it seems less clean and reproducible to setup.

**Comment by wlandau** [comment]
In that case, there's a fairly new package called [`default`](https://github.com/goldingn/default), which lets you change the default arguments of any function.
