### ISSUE TITLE
Dedicated vignette on wildcard templating

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#388]
Ref: #353. As @lorenzwalthert suggested, we should caution users to come up with wildcards that do not conflict with existing text in the commands.

**Comment by lorenzwalthert** [comment]
Thanks for opening this. In case you did not know: If want to refer to the exact comment in that issue, you can get the link from right clicking on "xx hours ago" in "lorenzwalthert commented xx hours ago" in the header of the comment. Learned that from Kirill 😊

**Comment by lorenzwalthert** [comment]
And let me know if I can assist on this, as it is in principle an easy task. But maybe it adds more overhead and you wanna do it yourself. 😊 Let me know.

**Comment by wlandau** [comment]
> If want to refer to the exact comment in that issue, you can get the link from right clicking on "xx hours ago"...

That is my usual preference, but I was away from a proper computer.

> And let me know if I can assist on this, as it is in principle an easy task.

Yes, I would love help. Thank you!

**Comment by lorenzwalthert** [comment]
So would you want to give an outline? Because I don't know drake very well (yet) so I want to make sure I can focus on the right aspects. 

I thought about:

* Quick description of what a wild card is and why it is useful (including recycling property).
* mention two functions `plan_analysis()` and `make_plan()` and their relationship. Not sure how to describe.
* Word of caution (reason for this issue) plus recommendations to use consistent wild cards, e.g. analysis__ and dataset__.
* Example (maybe simply taking from help file, or create a new one).

**Comment by lorenzwalthert** [comment]
Ok, will try to get us started this or next week on this. Most likely, I will miss a few things though and need help from you 😊

**Comment by wlandau** [comment]
I would really appreciate that, thank you!

**Comment by wlandau** [comment]
FYI: when you are ready for a PR, would you submit it to https://github.com/wlandau/drake-manual? I am moving all the vignettes and HTML widgets to a large online `bookdown`-powered user manual: (ref: https://github.com/ropensci/drake/issues/332#issuecomment-395267068).

Closing in favor of https://github.com/wlandau/drake-manual/issues/5.

**Comment by lorenzwalthert** [comment]
Sure
