### ISSUE TITLE
Assess the feasibility of CodeDepends for all the static code analysis

### ISSUE THREAD

**Issue by wlandau-lilly** [ropensci/drake#41]
Same as richfitz/remake#172.

**Comment by wlandau-lilly** [comment]
Apparently, [CodeDepends has been around since 2009](http://www.omegahat.net/CodeDepends/). Maybe it is only now being revived.

**Comment by wlandau-lilly** [comment]
```r
f <- function(){
  b = get("x", envir = globalenv())
  digest::digest(1234)
}
codetools::findGlobals(f) # Incorrectly ignores x and digest().
CodeDepends::getInputs(body(f)) # Still ignores x but does find digest().
```

**Comment by wlandau-lilly** [comment]
Could solve #25.

**Comment by wlandau-lilly** [comment]
After more thought, I have decided against replacing `codetools` with `CodeDepends`. Reasons:

1. Existing projects powered by `drake` may need to rerun from scratch.
2. The behavior of drake will not actually change much. Functions referenced with scoping rules `::` and `:::` would be detected, but after digging through `CodeDepends` and its documentation, I see no other potential improvement to #11.
3. `CodeDepends` does not actually replace `codetools`. In fact, it borrows `findGlobals()` internally.
4. It would be a huge headache to overhaul the internals of `drake`.

However, I am very eager to use `CodeDepends` to solve #9 and #25.

**Comment by wlandau** [comment]
I am considering reviving this issue after a recent conversation with @gmbecker at [R/Pharma 2018](http://rinpharma.com/).

`drake` now walks the AST manually because it has special code analysis needs, but it also calls `codetools` to find the globals. So we're walking the AST twice, which is slow. I think `CodeDepends` can handle all the code analysis in one pass.

But before that, I would strongly prefer to have

1. Easier compatibility between `CodeDepends` and the default `install.packages()`. `drake`'s long list of dependencies already turns off many users, and I would rather not add to the problem. Ref: https://github.com/duncantl/CodeDepends/issues/30, https://github.com/duncantl/CodeDepends/issues/34.
2. A robust `getInputs()`. `getInputs()` may already be robust enough, but there were [several issues](https://github.com/ropensci/drake/issues?utf8=%E2%9C%93&q=is%3Aissue+CodeDepends), and I have not checked all the variants of https://github.com/ropensci/drake/issues/268 recently.

After I can confirm all the above is resolved, a couple initial steps on my end will be to

1. Express the internal [`code_dependencies()`](https://github.com/ropensci/drake/blob/2ed11eb1c4e514adfb53ad54eb69b6cd475e2009/R/dependencies.R#L355) function in terms of `CodeDepends`.
2. See what kind of code analysis performance gains we accrue.

**Comment by gmbecker** [comment]
@wlandau The new way of installing bioconductor packages is via the `BiocManager` package which itself is on CRAN. Do you feel this is easier enough than the old way to make number 1 a less stringent requirement?

As for 2, I'm extremely confident that `CodeDepends` should be able to cover all the specialized needs `drake` has, it is just a question of how many custom handles `drake` will need to use vs where can improve the default handlers  generally in ways that also meet `drake`'s needs. That will be an ongoing conversation/collaboration between you and me, I think.

The specific issue you linked to, though, is covered, I think. The behavior now should be that if dplyr or tidyvese was loaded anywhere in the script that `getInputs()` knows about, the `dplyr` `filter()` will be assumed (ie NSE), otherwise it won't. If you want `drake` to err the other way and just always assume `filter()` means `dplyr::filter()` that is easily doable via a custom handler.

**Comment by wlandau** [comment]
1. As you mentioned in https://github.com/duncantl/CodeDepends/issues/34#issuecomment-400004052, `BiocManager` does smooth the installation process. In fact, since `drake` needs `CodeDepends` in `Suggests:` for `code_to_plan()`, I have added a [`BiocManager::install()` call](https://github.com/ropensci/drake/blob/82ed556434a1f6a1ba8c3a44c6e02e78d2ca077e/.travis.yml#L33) call in [`.travis.yml`](https://github.com/ropensci/drake/blob/master/.travis.yml). But given `drake`'s enormous list of dependencies, which unavoidably includes `igraph` and its own set of installation difficulties, I am just hyper vigilant about any slight increase to the friction of the installation experience. I am willing to reevaluate this position after seeing benchmarks of `CodeDepends`-driven code analysis.

To try to chip away at `drake`'s dependency problem, I have identified several packages that are currently only necessary for specific minor features: for example, `CodeDepends`, `visNetwork`, `networkD3`, `visNetwork`, and `webshot`. These packages are now in `Suggests:`, and `drake` [calls `assert_pkg()`](https://github.com/ropensci/drake/blob/82ed556434a1f6a1ba8c3a44c6e02e78d2ca077e/R/code_to_plan.R#L37) whenever a minor feature requires one.

https://github.com/ropensci/drake/blob/82ed556434a1f6a1ba8c3a44c6e02e78d2ca077e/R/utils.R#L1-L22

Is this an approach you would be willing to consider for `graph`?

2. It sounds like there has been enough progress to begin a proof of concept implementation for `drake`. The real deciding factor will be performance benchmarks, and I think we can get to the benchmarks without all the handlers necessarily in place from the beginning. Reopening.

**Comment by wlandau** [comment]
Hmm... I just saw that [`BiocManager` requires R >= 3.5.0](https://github.com/Bioconductor/BiocManager/blob/master/DESCRIPTION#L10), so it may be a while before `drake` can adopt things that depend in it.

**Comment by wlandau** [comment]
Also, #519 should speed up the code analysis (and remove the dependency on `codetools`). So although #41 is still worth investigating, I am less sure that we will need it.

**Comment by wlandau** [comment]
A major priority and direction for development right now is to reduce the number of package dependencies, especially for components as central and sensitive as code analysis. (related: #562, #563). I may revisit `CodeDepends` for this purpose at some point, but I do not forsee it becoming a backend for `drake`'s core dependency detection functionality any time soon. To achieve the possible speed gains mentioned above, I would actually prefer to find a base R alternative to `codetools::findGlobals()`.

On the other hand, I think people really appreciate functionality that converts `drake` plans to and from scripts and notebooks (ref: #505, https://github.com/ropensci/drake/issues/193#issuecomment-433674726). `CodeDepends` plays a central role there, so it will remain in "Suggests:" for the forseeable future.
