### ISSUE TITLE
Deprecate non-future parallelism?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#441]
There is duplication of ideas and effort in the multiple forms of parallelism supported by drake/drake-via-future, adding to (at least my) confusion over how to best use the package. I think it would be best to just use `future` for parallelism then have a different argument for transient/persistent/staged.

This requires (at least):
- [ ] Adding support for staged parallelism using `future`.
- [ ] Adding a `future` evaluator for using `Makefile` parallelism. i.e. `future::plan(makefile)` OR deprecating `Makefile` parallelism.
- [ ] Adding deprecation messages in the relevant functions

Also mentioned here but didn't get it's own issue: https://github.com/ropensci/drake/issues/227

**Comment by wlandau** [comment]
It's a good thought, but I do not think it is time to deprecate any parallel `drake` is still in a brainstorming phase when it comes to HPC. New paths and technologies are emerging fast, and it is not yet clear where `drake` will settle. Also, in `future`-based parallelism specifically, there is extra overhead to make sure workers can be deployed remotely. This does not bode well for imports or large numbers of quick targets.

**Comment by wlandau** [comment]
Lastly, I have actually been trying to get rid of staged parallelism. I could not quite do it for the last CRAN release because there are some projects that benefit (e.g. https://github.com/ropensci/drake/issues/369#issuecomment-386814320), and for projects that require remote workers, I believe transient workers (`"future"` parallelism) is uniformly better.
