### ISSUE TITLE
R6 priority queue in `future` parallelism doesn't seem to obey `targets` argument to make

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#445]
In my example I'm seeing:
```r
Browse[2]> queue$size()
[1] 29398
Browse[2]> length(config$targets)
[1] 16768
```

**Comment by wlandau** [comment]
The `targets` argument to `make()` is forgiving in the sense that you do not need to list all the dependendcies. You named 16768 targets, but `drake` needs to check/build `29398 - 16768` dependencies first. The [graph is pruned so that the `targets` argument names the final/downstream nodes](https://github.com/ropensci/drake/blob/871439bbba419b6308984173e64a5e732f550c97/R/graph.R#L76), and the [priority queue gets *all* the nodes](https://github.com/ropensci/drake/blob/master/R/priority_queue.R#L3).
