### ISSUE TITLE
Preprocess up-to-date targets in `mc_master`

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#455]
I believe this will go a long way to solving the issue I was having in #449.

You probably could literally call `outdated` in this function, being careful to ensure `outdated`  uses `jobs_imports` wherever it lightly parallelizes.

**Comment by wlandau** [comment]
It gets tricky because sometimes `mc_master()` is used to process the imports at the same time. But maybe we can remove up-to-date targets [from the schedule here](https://github.com/ropensci/drake/blob/5cfd7e94ab87d551615e67b3f3e4b0a05d2c4890/R/make.R#L338). That way, they will never get added to the priority queue.

**Comment by kendonB** [comment]
@wlandau If all targets are up to date, `make_targets` still runs `run_parallel_backend` unnecessarily. Since the worker launches but ends up doing nothing, this can still take a long time if the HPC scheduler doesn't launch your job right away. Would checking the length (however you do that for an igraph) of `config$schedule` would do it?

**Comment by wlandau** [comment]
Sure. For distributed backends, it does make sense to check the schedule in `make_targets()`.

**Comment by wlandau** [comment]
Fixed in de44794c16509a39c38f1a40dc7b610960fb4f61.
