### ISSUE TITLE
Track dependencies to functions in report files

### ISSUE THREAD

**Issue by norival** [ropensci/drake#458]
Hi!

I have a report file that is tracked by drake, all targets loaded with `loadd` are marked as dependencies. However, I use some functions in this file, and they are not tracked. Is it normal behaviour?

I know I could make these functions generate some targets and load them within the report file, but I feel it coul be useful to track the functions directly.

**Comment by wlandau** [comment]
Yes, this is normal and intentional. My goal with `knitr` reports was to not only connect them in a `drake` pipeline, but also allow users to knit them in a non-`drake` session (without all the imports loaded) as long as the `drake` cache is fully populated. That means you will have to `loadd()` or `readd()` those functions explicitly as you would ordinary targets. Either that or maybe define them in the report itself if you do not need them elsewhere.

**Comment by norival** [comment]
Ok, thank you for your answer :)
