### ISSUE TITLE
.drake/config/hash_algorithm': No such file or directory when empty .drake folder is present

### ISSUE THREAD

**Issue by PedramNavid** [ropensci/drake#514]
When using drake, a `.drake` folder is created with a `.gitignore` file that ignores all files. 

However, drake will fail if an empty `.drake` folder exists. This means when cloning a repo that uses drake, `make(plan)` will fail unless the `.drake` folder and the accompanying `.gitignore` file is deleted.

Perhaps there are other checks that can be performed here before attempting to load the cache. I am thinking a simple `file.exists(hash_algo_file)` might suffice. 
https://github.com/ropensci/drake/blob/master/R/cache.R#L162

I'd be happy to submit a PR for this if you concur.

Simple reprex:

```
> dir.create('tmp')
> setwd('tmp')
> dir.create('.drake')
> library(drake)
> plan <- drake_plan(x = rnorm(100))
> make(plan)
Error in file(file, "r") : cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file '/Users/pedram/tmp/tmp/.drake/config/hash_algorithm': No such file or directory
>
```

**Comment by wlandau** [comment]
Thanks for the report! I totally agree. I was initially concerned about [other cache types](http://richfitz.github.io/storr/articles/storr.html#supported-backends), but this issue only affects the [default `storr_rds()` cache](http://richfitz.github.io/storr/reference/storr_rds.html). And as you say, https://github.com/ropensci/drake/blob/ae17b46f463d7e289acc89605df1668906ae6317/R/cache.R#L162 is the right place for a more informative error message. A PR and a unit test would be great if you have the time.

If the cache is otherwise corrupted during a download, https://github.com/richfitz/storr/issues/55 may also help.

**Comment by wlandau** [comment]
So when `drake_fetch_rds()` fails inside `this_cache()` , my current thinking is to

1. Quit with an informative error message if `force` is `FALSE`.
2. Warn the user, delete the old cache, and use a new one if `force` is `TRUE`.

**Comment by wlandau** [comment]
On second thought, the informative error message should be enough.

**Comment by wlandau** [comment]
Fixed via https://github.com/ropensci/drake/commit/e9df8327993e8244a351fc1374f9fe881b576aa8. I know I said I would accept a PR, and I will still consider it if you think this issue should be solved differently. I just wanted to knock this one out before I go on vacation on Sept 15 - Oct 1.

**Comment by PedramNavid** [comment]
I was having trouble figuring out how to create a test case so this looks great, thanks for this!
