### ISSUE TITLE
It is not obvious where target objects in Rmd files come from

### ISSUE THREAD

**Issue by nathaneastwood** [ropensci/drake#523]
This isn't necessarily an issue, but I felt it was too open ended for SO.

I really like `drake` and the concepts behind it. I have an analysis piece I am currently working on but I have a question with regards to Rmarkdown reports. If we look at `drake_example("mtcars")`, the `report.Rmd` file contains objects such as `small`, `large` and `coef_regression2_small`. Unless you know how `drake` works, it is not at all obvious where these objects come from. This is very similar to when you have a `no visible binding for global variable [variable name]` error in an `R CMD Check`. Does `drake` provide any explicit or visual way of showing where an object has come from using `loadd()` and `readd()`? Or do I need to provide options to the function parameters `path`, `namespace`, etc.?

My thinking behind this is that working within a team, it is unreasonable to expect everyone to go and learn the `drake` API (especially if they are non-R users) and they should just be able to view a report and see where objects have come from / how they were generated. Keeping an entire analysis piece within an `.Rmd` file gives you this because you read in, manipulate, plot, etc. the data all within that document but `drake` extracts that specificity. I appreciate that there are visualisation tools within `drake` so maybe a piece of advice would be to keep this in your `README` file?

Ultimately I am looking for advice in this area and I don't think it's made entirely clear from the book.

**Comment by wlandau** [comment]
Thanks for the feedback. I often take issues with R Markdown and scripts for granted, and I am still trying to figure out the best way to explain what `drake` does here.

> Unless you know how drake works, it is not at all obvious where these objects come from.

True, and I am sorry, but this is unlikely to change. `drake` is opinionated. It deliberately nudges you to include R Markdown reports as steps in the pipeline rather than using `knitr` as your workflow manager. The idea is to offload expensive computations to upstream `drake` targets so the reports compile really fast. And the whole pipeline comes with a cache, usually a hidden `.drake/` folder. The report file uses the cache in those calls to `loadd()` and `readd()` in active code chunks. Those calls serve 2 purposes.

1. Declare the dependencies of the report so `drake` can compile it at the correct step in the pipeline.
2. If the cache is already present from a previous call to `drake::make()`, you can `render()` the report by itself without needing to go through `drake` again.

From (2), as long as the `.drake/` cache is present, your collaborators can still compile the report without knowing what `loadd()` and `readd()` actually do. And if they want to know, those are the only `drake` API functions they need to understand to know exactly what the report itself is doing.

> Does drake provide any explicit or visual way of showing where an object has come from using loadd() and readd()?

You can use the `show_source` argument to print out a description of how the loaded targets are generated.

> Or do I need to provide options to the function parameters path, namespace, etc.?

Not unless you supply a custom cache. By default, `load()` and `readd()` automatically find the `.drake/` folder.

> maybe a piece of advice would be to keep this in your README file?

I am planning to expand the manual to cover R Markdown and related issues in more detail: https://github.com/ropenscilabs/drake-manual/issues/33. Could we follow up there?
