### ISSUE TITLE
Erroneous circular workflow error when using NSE in function

### ISSUE THREAD

**Issue by mdlincoln** [ropensci/drake#578]
Firstly, thanks for an awesome package! 

I think I've found a problem with circularity checks and NSE. In this example, I use dplyr to create a new column `a`, and then call a modification on that column.

drake's `deps_code` registers this data frame column `a` as a global dependency, even though it's not, really. Because it happens to be named the same as the eventual target, drake throws a circularity error.

``` r
library(drake)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

create_set <- function(df) {
  df %>% 
    mutate(a = 1) %>% 
    mutate(b = a + 1)
}

iris_plan <- drake_plan(
  a = create_set(iris)
)

make(iris_plan)
#> Error in check_drake_graph(graph = config$graph): Circular workflow: there is a target that ultimately depends on itself. Cycles:
#>   a create_set

deps_code(create_set)
#> $globals
#> [1] "mutate" "a"
```

<sup>Created on 2018-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
## Explanation

It would be difficult for `drake` to properly account for NSE variables because it uses static code analysis to detect dependencies. Specifically, `drake` [walks the ASTs](http://adv-r.had.co.nz/Expressions.html#ast-funs) of each command and imported function. It does not actually execute those `mutate()` calls when it analyzes your code, so it cannot tell if `a` is supposed to be a target or a just a column in `df`.

So I do not think `drake` should try to figure out NSE. Without special precautions, `drake` incorrectly detects NSE variables, and we end up with the issue you raised. But if we try to single them out and exclude them, we end up with unexpected edge cases like #421. No matter what we do, `drake` is sometimes going to get the wrong answer. All we can do is make the failures as unsurprising as possible. If simple use cases fail less often than edge cases, then `drake`'s errors are well-calibrated. 

## What you can do

You can use `ignore()` to blacklist pieces of commands and imported functions from dependency detection.

``` r
library(drake)
library(dplyr)

create_set <- function(df) {
  df %>% 
    mutate(a = 1) %>% 
    mutate(b = ignore(a) + 1)
}

iris_plan <- drake_plan(
  a = create_set(iris)
)

make(iris_plan)
#> target a
```

## What I will do

I will make the error message more informative. It should at least mention `ignore()` and possibly point to this issue.

**Comment by mdlincoln** [comment]
Oh thanks, I didn't realize that `ignore()` even existed! There's just so many exported functions in this package. Having this in the error message, and maybe some heading in the manual would be great.

**Comment by scientificbruno** [comment]
Is there a way to configure drake to ignore the contents of a function (_e.g._ in the example above, the content of `create_set()`) and just focus on what is included in the `drake_plan()` call (_e.g._ `create_set(iris)`)? In other words, I want drake to trust that any dependencies will be given as arguments to the function call and ignore whatever the function is doing internally.

**Comment by wlandau** [comment]
Not easily, and that's by design. A couple hacks:

1. Wrap everything in all your functions inside `ignore()`.
2. Wrap your workflow in a custom package (example: https://github.com/ropensci/drake/issues/685) and do not call `expose_imports()`.
