### ISSUE TITLE
Bug in the condition trigger?

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#616]
Why does the following work? I was expecting it to result in "all targets are up to date".

``` r
library(drake)

plan <- drake_plan(
  x = target(
    1 + 1,
    trigger(condition = FALSE, mode = "condition")
  )
)
#> Warning: Converting double-quotes to single-quotes because the
#> `strings_in_dots` argument is missing. Use the file_in(), file_out(), and
#> knitr_in() functions to work with files in your commands. To remove this
#> warning, either call `drake_plan()` with `strings_in_dots = "literals"` or
#> use `pkgconfig::set_config("drake::strings_in_dots" = "literals")`.

make(plan, "x")
#> target x
```

<sup>Created on 2018-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
Good question. That's because the target's value does not exist yet. If a target is missing from the cache, there is no trigger that will stop it from building.

``` r
library(drake)
plan <- drake_plan(
  x = target(
    1 + 1,
    trigger(condition = FALSE, mode = "condition")
  ),
  strings_in_dots = "literals"
)
make(plan)
#> target x
make(plan)
#> All targets are already up to date.
plan$command <- "12345"
make(plan)
#> All targets are already up to date.
make(plan)
#> All targets are already up to date.
```

<sup>Created on 2018-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I believe this is the correct behavior for most situations. Before adding a "hard skip" option, I would need to be convinced that the need is significant enough.

If I were to implement it, I would probably use `trigger(condition = FALSE, mode = "hard-skip")`. But I am resistant because it would complicate both the tests and the logic in [`should_build_target()`](https://github.com/ropensci/drake/blob/9426d1b2cb63ab157ca1d35ad197727e29f27235/R/triggers.R#L212).
