### ISSUE TITLE
Functions that depend on targets

### ISSUE THREAD

**Issue by ldecicco-USGS** [ropensci/drake#632]
I'm not really sure what is the exact term to use.... Here's the scenario:

Good:
```r
library(drake)

my_fun <- function(){
  other_fun <- function(){
    thing_in_drake
  }
}

plan <- drake_plan(
  thing_in_drake = 1,
  my_fun()()
)
make(plan)
readd(drake_target_1)
[1]
```
Not good:
```r
plan2 <- drake_plan(
  thing_in_drake = 1,
  other_thing = my_fun()()
)

make(plan2)
target other_thing
fail other_thing
Error: Target `other_thing` failed. Call `diagnose(other_thing)` for details. Error message:
  object 'thing_in_drake' not found
```

Why does specifying a target name in the second plan not find `thing_in_drake`?

**Comment by wlandau** [comment]
That's interesting. As it turns out, this is because imported functions cannot take targets as dependencies. `thing_in_drake` is really a target, so it should not be a global symbol inside `my_fun()` or `other_fun()`. The dependency relationship below does not throw an error, but it is not actually valid.

``` r
library(drake)

my_fun <- function(){
  other_fun <- function(){
    thing_in_drake
  }
}

plan <- drake_plan(
  thing_in_drake = 1,
  my_fun()()
)

config <- drake_config(plan)
vis_drake_graph(config)
```

![](https://i.imgur.com/HDDWYkd.png)

<sup>Created on 2018-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I suppose `drake` could theoretically run through all the imports and check that they do not depend on any targets, but that could be computationally expensive.

This is related to the concept of "pure functions" and their traditional role in pipeline tools, but depending on global symbols might be slightly different.

**Comment by wlandau** [comment]
In https://github.com/ropensci/drake/commit/2e36151369ec929240d5f0231ace227dbdcb962a, I think I found the right tradeoff between reducing confusion and reducing computation. Now, when `drake` tries to detect dependencies of imported functions, it will ignore targets in the plan. Nothing is stopping you from writing targets inside functions anyway, and you will still get an error if you do so. However, the graph visualization is far more useful now.

``` r
library(drake)
global_import <- 1
my_fun <- function(){
  global_import
  target_in_plan
}
plan <- drake_plan(
  target_in_plan = 1,
  x = my_fun()
)
config <- drake_config(plan)
vis_drake_graph(config, build_times = "none")
```

![](https://i.imgur.com/Vxenlhu.png)

<sup>Created on 2018-12-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
