### ISSUE TITLE
Target can't serve as argument to conditional trigger

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/drake#704]
I think this explains the error with using a dataframe of existing tweets to check if there are new ones from the same user.

``` r
library(drake)

add <- function(a, b) {
  a + b
}

square <- function(x) {
  x ^ 2
}

plan <- 
  drake_plan(
    first = add(2, 3),
    second = square(first)
  )

make(plan)
#> target first
#> target second


# Use the target `first` as the sample size for this trigger
rand_is_even <- function(samp_size) {
  num <- sample(samp_size, 1)
  
  if (num %% 2 == 0) {
    TRUE
  } else {
    FALSE
  }
}

loadd(first)
rand_is_even(first)
#> [1] FALSE

plan <- 
  drake_plan(
    first = add(2, 3),
    second = target(
      command = square(first),
      trigger = trigger(
        condition = rand_is_even(first)
      )
    )
  )

make(plan)
#> Unloading targets from environment:
#>   first
#> Warning in if (is_file(target)) {: the condition has length > 1 and only
#> the first element will be used
#> Warning in if (!cache$exists(key = target, namespace = "meta")) {: the
#> condition has length > 1 and only the first element will be used
#> Warning in if (!cache$exists(key = target, namespace = "meta")) {: the
#> condition has length > 1 and only the first element will be used
#> Error: 'key' must be a scalar
```

<sup>Created on 2019-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
Ah, yes, now I remember. This was a bug in version 6.2.1. I had goofed up the way dependencies of triggers were tracked. It is fixed in the development version. I forget which commit that was, but it is in the news: https://github.com/ropensci/drake/blob/master/NEWS.md#bug-fixes. I will add your example as a unit test for good measure.

**Comment by wlandau** [comment]
`drake` did have a test for this before, but a little redundancy is good for tests this fast, and this reprex is too nice to waste.

**Comment by wlandau** [comment]
Yup, the message is intentional when `verbose > 0L`. I first implemented triggers for massive workflows several versions ago when checking dependencies took a really long time. The main use case was `trigger(file = FALSE, depend = FALSE, command = FALSE)`. I can see how the message would be annoying if you have a legitimate use case, but I am not sure we should skip the message for `verbose = 1L`. I could be convinced though.

**Comment by aedobbyn** [comment]
Gotcha. I'd be pro disabling for `verbose = 1L` since it doesn't seem like users should be warned for using a feature as intended but your call of course!
