### ISSUE TITLE
FAQ: Functions as data

### ISSUE THREAD

**Issue by tmastny** [ropensci/drake#706]
I've come across examples where functions are parameters to the drake workflow. The following is a small example demonstrating this case.

Maybe this can be a part of the FAQ, or maybe you could suggest a better way to handle this pattern.

``` r
library(drake)
library(rlang)
#> Warning: package 'rlang' was built under R version 3.5.2
data_to_download <- c(
  "data1",
  "data2",
  "data3",
  "data4"
)

get_data <- function(.name) {
    mtcars
}

process_data1 <- function(x) x
process_data2 <- function(x) x$cyl
process_data3 <- function(x) x$disp
process_data4 <- function(x) x$hp

fns <- exprs(
  process_data1,
  process_data2,
  process_data3,
  process_data4
)

plan <- drake_plan(
  data = target(
    get_data(name),
    transform = map(
      name = !!data_to_download
    )
  ),
  cleaned = target(
    fn(data),
    transform = map(data, fn = !!fns)
  )
)
plan
#> # A tibble: 8 x 2
#>   target                             command                    
#>   <chr>                              <chr>                      
#> 1 data_.data1.                       "get_data(\"data1\")"      
#> 2 data_.data2.                       "get_data(\"data2\")"      
#> 3 data_.data3.                       "get_data(\"data3\")"      
#> 4 data_.data4.                       "get_data(\"data4\")"      
#> 5 cleaned_process_data1_data_.data1. process_data1(data_.data1.)
#> 6 cleaned_process_data2_data_.data2. process_data2(data_.data2.)
#> 7 cleaned_process_data3_data_.data3. process_data3(data_.data3.)
#> 8 cleaned_process_data4_data_.data4. process_data4(data_.data4.)

make(plan)
#> target data_.data1.
#> target data_.data2.
#> target data_.data3.
#> target data_.data4.
#> target cleaned_process_data1_data_.data1.
#> target cleaned_process_data2_data_.data2.
#> target cleaned_process_data3_data_.data3.
#> target cleaned_process_data4_data_.data4.
```

<sup>Created on 2019-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

This workflow still provides dependencies on the `process_data*` functions, so if one changes you don't have to rebuild the entire plan.
<img width="930" alt="screen shot 2019-02-02 at 2 31 33 pm" src="https://user-images.githubusercontent.com/20732748/52169023-7a2c1e00-26f7-11e9-8762-274f4b103940.png">

**Comment by wlandau** [comment]
Such an excellent point!

> This workflow still provides dependencies on the process_data* functions, so if one changes you don't have to rebuild the entire plan.

Exactly! In `drake` projects, sometimes we do not want to reuse the same function too often. We are pushing back a bit against Tidyverse function-oriented programming best practices in order to help keep targets up to date. The right tradeoff is different from project to project, and I think `sankey_drake_graph()` can help. Below, the taller boxes have more dependencies (or reverse dependencies) than the other nodes, and this helps identify parts of the pipeline where targets are most likely to break.

``` r
library(drake)
library(rlang)

data_to_download <- c(
  "data1",
  "data2",
  "data3",
  "data4"
)

get_data <- function(.name) {
    mtcars
}

process_data <- function(x) {}

plan <- drake_plan(
  data = target(
    get_data(name),
    transform = map(
      name = !!data_to_download
    )
  ),
  cleaned = target(
    process_data(data),
    transform = map(data)
  )
)

config <- drake_config(plan)
sankey_drake_graph(config)
```

![](https://i.imgur.com/yxLixXx.png)

``` r


process_data1 <- function(x) x
process_data2 <- function(x) x$cyl
process_data3 <- function(x) x$disp
process_data4 <- function(x) x$hp

fns <- exprs(
  process_data1,
  process_data2,
  process_data3,
  process_data4
)

plan <- drake_plan(
  data = target(
    get_data(name),
    transform = map(
      name = !!data_to_download
    )
  ),
  cleaned = target(
    fn(data),
    transform = map(data, fn = !!fns)
  )
)

config <- drake_config(plan)
sankey_drake_graph(config)
```

![](https://i.imgur.com/33bz4uq.png)

``` r

get_data1 <- function(x) x
get_data2 <- function(x) x + 1
get_data3 <- function(x) x + 2
get_data4 <- function(x) x + 3

data_fns <- exprs(
  get_data1,
  get_data2,
  get_data3,
  get_data4
)

plan <- drake_plan(
  data = target(
    data_fn(name),
    transform = map(
      name = !!data_to_download,
      data_fn = !!data_fns
    )
  ),
  cleaned = target(
    fn(data),
    transform = map(data, fn = !!fns)
  )
)

config <- drake_config(plan)
sankey_drake_graph(config)
```

![](https://i.imgur.com/irzv3S5.png)

<sup>Created on 2019-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I have tagged this issue as a frequently asked question. I think that is all that can be done in `drake` itself, so I am closing the issue. Let's follow up in the [repo of the manual](https://github.com/ropenscilabs/drake-manual). I think we can up with some useful guidance in the chapter on best practices, maybe even the chapter on plans too.
