### ISSUE TITLE
Toggle breakpoint in a target's execution in RStudio

### ISSUE THREAD

**Issue by htlin** [ropensci/drake#738]
Hi,

As title, is it possible to toggle breakpoint in a target's execution in RStudio, either on the target itself or my custom functions called within a target?

Thanks!
Harris.

**Comment by wlandau** [comment]
Good question. You can always set `browser()`/`debug()` breakpoints in your custom functions right before `make()`. In addition,  `drake_debug()` builds a single target with a breakpoint at the start of the command. To dive further into functions nested inside the command, you will need `browser()` or `debug()`. Since `drake` is file-based, it does not listen to the breakpoints you set by clicking on the margins of code files in the RStudio IDE..

**Comment by htlin** [comment]
Ok that works too, thanks!
