### ISSUE TITLE
knitr file paths

### ISSUE THREAD

**Issue by htlin** [ropensci/drake#742]
I have some issues with the `rmarkdown::render`, first of all this simple version works:
```
sReportMain = rmarkdown::render(
    knitr_in("report-main.Rmd"),
    output_file = file_out("report-main.html")
  )
```

However if the input report is in any sub-directory like this:
```
sReportMain = rmarkdown::render(
    knitr_in("somedir/report-main.Rmd"),
    output_file = file_out("report-main.html")
  )
```
Then the report still got produced BUT I would get a warning when running `vis_drake_graph`:
> Warning messages:
> 1: Missing files for target sReportMain:
>   report-main.html 

The default output directory happens to share the input directory.
Also I am having other problems when I use the `output_dir` argument of `rmarkdown::render`, but let's see if you have any insights to this first, thanks!

**Comment by wlandau** [comment]
Yeah, like you said, `output_file` assumes the file is in the same directory as the input. `knitr_in()`, on the other hand, requires a real path. So in your example above, `drake` is looking for the HTML report in your working directory when `render()` actually wrote it to `somedir`. You can use `output_dir` to make sure `drake` and `rmarkdown` are on the same page.

```r
sReportMain = rmarkdown::render(
  knitr_in("somedir/report-main.Rmd"),
  output_file = file_out("somedir/report-main.html"),
  output_dir = "."
)
```

Without `output_dir = "."`, the call to `render()` fails. I suspect this is because `rmarkdown::render(knitr_in("somedir/report-main.Rmd"), output_file = file_out("somedir/report-main.html"))` tries to create `somedir/somedir/report-main.html` without creating `somedir/somedir` first.

**Comment by htlin** [comment]
That one still doesn't work for me, as I found that `render` has this behavior:
> output_dir: ... If a path is provided with a filename in output_file the directory specified here will take precedence.

So if I do the following it worked for me:
```
sReportMain = rmarkdown::render(
  knitr_in("somedir/report-main.Rmd"),
  output_file = file_out("somedir/report-main.html"),
  output_dir = "somedir"
)
```

Next thing I tried is to refactor the paths out into variables:
```
sReportMain = rmarkdown::render(
  knitr_in(file.path(kRPath, "report-main.Rmd")),
  output_file = file_out(file.path(kOutputPath, "report-main.html")),
  output_dir = kOutputPath,
  quiet = TRUE
)
```
However the plan failed because it can't recognize the dependency, I had to use `!!` to get it back working again:
```
sReportMain = rmarkdown::render(
  knitr_in(!!(file.path(kRPath, "report-main.Rmd"))),
  output_file = file_out(!!(file.path(kOutputPath, "report-main.html"))),
  output_dir = kOutputPath,
  quiet = TRUE
)
```

Is this the correct way of setting this up now?

**Comment by wlandau** [comment]
Either the first or third alternative seems fine. `file_out()` needs to have the literal full path of the file before `make()` is called.

**Comment by jl5000** [comment]
Setting both output_dir and output_file has resolved a similar problem I was having with DataExplorer::create_report().
