### ISSUE TITLE
Wrapper functions appear as 'missing'

### ISSUE THREAD

**Issue by dbarneche** [ropensci/drake#747]
Hello,

I am transitioning from [remake](https://github.com/richfitz/remake) to drake. So I downloaded the main simple example, and modified the file structure, `R/plan.R` and `R/setup.R`:
https://github.com/dbarneche/drake-example

The main difference here is that I used wrapper functions to clean the drake plan in [`R/plan.R`](https://github.com/dbarneche/drake-example/blob/master/R/plan.R). So the functions are all stashed away in [`R/setup.R`](https://github.com/dbarneche/drake-example/blob/master/R/setup.R)

After running `source('make.R')` in R, everything is created nicely as it should. The issue though arises when I run `drake::vis_drake_graph()` right after that. For some reason, my functions appear as missing (purple triangles) in the .html: see below

<img width="869" alt="screen shot 2019-02-20 at 10 16 16 am" src="https://user-images.githubusercontent.com/3580907/53085258-6146a980-34fa-11e9-8a81-73ff1c69b268.png">

So I was wondering if someone could explain why that's the case?

The full reproducible code on a Mac Terminal (just make sure that all packages listed in `make.R` are already installed):

```
cd
git clone git@github.com:dbarneche/drake-example.git
cd drake-example
R
source('make.R')
drake::vis_drake_graph()
```

Thanks for your help!

**Comment by wlandau** [comment]
One odd feature of `drake` <= 6.2.1 is that you can call `vis_drake_graph()` with no arguments because `config` is read from the cache by default. I never should have allowed this. Please generate a new `config` object with `drake_config()`, which grabs your environment and all the functions in it. In the development version (CRAN release coming mid-March) `vis_drake_graph()` and friends have no default value of `config`.

```r
config <- drake_config(plan)
vis_drake_graph(config)
```
