### ISSUE TITLE
dependency on ggraph is not properly declared

### ISSUE THREAD

**Issue by skolenik** [ropensci/drake#779]
> drake_ggraph(config)
    Error: package ggraph not installed. Please install it with install.packages("ggraph").
    > packageVersion("drake")
    [1] ‘7.0.0’

It looks like `ggraph` is being checked with `assert_pkg()` in `R/vis-ggraph.R`, but it is not explicitly mentioned in `NAMESPACE`.

**Comment by wlandau** [comment]
Yup, the error is sometimes annoying, but believe it or not, it is a conscious decision. `drake` is a large package, and if all the [optional packages](https://github.com/ropensci/drake/blob/ae093a068c1be05bcb217de07b79882c0643e156/DESCRIPTION#L85-L110) were strictly required, it would be brittle and difficult to install. `ggraph` is optional because it is only required for `drake_ggraph()` and `render_drake_ggraph()`, neither of which are actually required to plan or build targets. Perhaps there is a better way to manage the large code base and scope, but so far, I do not regret the current approach.
