### ISSUE TITLE
map using initial parameter only follows through for one stage

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#791]
The association between `param` and `results_one` seems to get lost here.

``` r
library(drake)
drake_plan(
  data = target(
    get_data(param),
    transform = map(param = c(1, 2))
  ),
  results_one = target(
    get_results(data),
    transform = map(param)
  ),
  results_two = target(
    get_more_results(results_one),
    transform = map(param)
  )
)
#> # A tibble: 6 x 2
#>   target        command                      
#>   <chr>         <expr>                       
#> 1 data_1        get_data(1)                  
#> 2 data_2        get_data(2)                  
#> 3 results_one_1 get_results(data_1)          
#> 4 results_one_2 get_results(data_2)          
#> 5 results_two_1 get_more_results(results_one)
#> 6 results_two_2 get_more_results(results_one)
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by bomeara** [comment]
I might be having a similar issue (but I'm a novice with respect to `map`):

From the manual: 

```
drake_plan(x = target(get_data(y), transform = map(y = c("a", "b", "c"))))
```

returns

```
# A tibble: 3 x 2
  target command
  <chr>  <expr>
1 x_.a.  get_data("a")
2 x_.b.  get_data("b")
3 x_.c.  get_data("c")
```

but 

```
z <- c("a", "b", "c")
drake_plan(x = target(get_data(y), transform = map(y = z)))
```

returns just 

```
# A tibble: 1 x 2
  target command
  <chr>  <expr>
1 x_z    get_data(z)
```

Perhaps even easier: 

```
drake_plan(x = target(get_data(y), transform = map(y =c(1:3))))
drake_plan(x = target(get_data(y), transform = map(y =c(1,3))))
```

Return very different things (tibble with `get_data(1:3)` in first case and both `get_data(1)` and `get_data(3)` in second).

**Comment by wlandau** [comment]
@kendonB,

Transformations have their own graph topology independent from commands. This restriction keeps the DSL from assuming too much, and it protects us from more nefarious edge cases. In your plan, `param` connects the target groups as below.

![Capture](https://user-images.githubusercontent.com/1580860/54822853-4f346400-4c7c-11e9-9999-84be2085d6d0.PNG)

Without an edge from `results_one` to `results_two`, there is no directed path from `results_one` to `results_two`. In other words, because transformations and commands are separately analyzed, `results_one` is not upstream of `results_two` in the DSL.

Solution: to get the correct symbol substitutions, just mention `results_one` in `map()`. With the appropriate edge directions, `param` will tag along too (see `results_three` below).

``` r
library(drake)
drake_plan(
  data = target(
    get_data(param),
    transform = map(param = c(1, 2))
  ),
  results_one = target(
    get_results(data),
    transform = map(param)
  ),
  results_two = target(
    get_more_results(results_one),
    transform = map(results_one)
  ),
  results_three = target(
    get_more_results(results_one, param),
    transform = map(results_one)
  )
)
#> # A tibble: 8 x 2
#>   target                      command                           
#>   <chr>                       <expr>                            
#> 1 data_1                      get_data(1)                       
#> 2 data_2                      get_data(2)                       
#> 3 results_one_1               get_results(data_1)               
#> 4 results_one_2               get_results(data_2)               
#> 5 results_two_results_one_1   get_more_results(results_one_1)   
#> 6 results_two_results_one_2   get_more_results(results_one_2)   
#> 7 results_three_results_one_1 get_more_results(results_one_1, 1)
#> 8 results_three_results_one_2 get_more_results(results_one_2, 2)
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
@bomeara,

You can use `!!` from [tidy evaluation](https://tidyeval.tidyverse.org/) to get the desired plans.

``` r
library(drake)
drake_plan(x = target(get_data(y), transform = map(y = !!c(1:3))))
#> # A tibble: 3 x 2
#>   target command     
#>   <chr>  <expr>      
#> 1 x_1L   get_data(1L)
#> 2 x_2L   get_data(2L)
#> 3 x_3L   get_data(3L)
z <- c("a", "b", "c")
drake_plan(x = target(get_data(y), transform = map(y = !!z)))
#> # A tibble: 3 x 2
#>   target command      
#>   <chr>  <expr>       
#> 1 x_.a.  get_data("a")
#> 2 x_.b.  get_data("b")
#> 3 x_.c.  get_data("c")
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Why tidy evaluation? Because we create a `drake` plan, we are [metaprogramming](http://adv-r.had.co.nz/Expressions.html). We are writing code to create code. When we substitute stuff inside commands, sometimes we want literal symbol names, and other times we want to get values from variables. The former case is the default, and we can invoke the latter with the `!!` operator.

The [section on grouping variables](https://ropenscilabs.github.io/drake-manual/plans.html#grouping-variables) discusses a bit more.
