### ISSUE TITLE
Load target from arbitrary working directory

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#793]
I am about to create a presentation in which I want to use certain targets.

Now my presentation directory is placed in a hierarchical way along the project directory:

```
| --- project 1
  --- project 2
  --- presentation
   | --- presentation.Rmd
```

Now when I try to load a target from the cache of project one, I get 

```r
drake::loadd(cache = "../project1/.drake", 
             target1)
Error: $ operator is invalid for atomic vectors
```

I can load the target without problems in the respective project.
When trying to source `_drake.R` before, I also get an error:

```
Error in file(filename, "r", encoding = encoding) : cannot open the connection
```

Is this way of loading targets not supported?

**Comment by wlandau** [comment]
In `loadd()`, I recommend using the `path` argument rather than `cache`, e.g. `loadd(path = "../project1/.drake")`. Alternatively, you could use `loadd(cache = storr::storr_rds("../project1/.drake"))`, but going through `storr` is extra work.

`_drake.R` is designed to support the `r_*()` functions that require a `drake_config()` argument. There is no `r_loadd()`, and `loadd()` only requires a `config` if `deps = TRUE`.
