### ISSUE TITLE
Surface the user manual in the pkgdown navbar?

### ISSUE THREAD

**Issue by maelle** [ropensci/drake#797]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

I'm wondering whether the pkgdown navbar of `drake` should link to the user's manual directly (as a whole, not only the FAQ). The reasons I'm not even making a PR are
* you might disagree
* how would you call the manual in the navbar? "User manual"? It seems not very informative compared to "Reference" (I wouldn't know on which one to click).

## Other question

In general, how would you explain why you chose to have an user manual rather than a bunch of vignettes? Because you want the website to "serve as a quicker reference."?

**Comment by wlandau** [comment]
> I'm wondering whether the pkgdown navbar of drake should link to the user's manual directly (as a whole, not only the FAQ).

Good idea. I support this.

> How would you call the manual in the navbar? 

From left to right, I think we could have these navbar links:

- Functions: https://ropensci.github.io/drake/reference/index.html
- Resource links: https://ropensci.github.io/drake/articles/drake.html
- Full manual: https://ropenscilabs.github.io/drake-manual
- FAQ: https://ropenscilabs.github.io/drake-manual/faq.html
- News: https://ropensci.github.io/drake/news/index.html

And I could definitely be convinced to do this differently.

> In general, how would you explain why you chose to have an user manual rather than a bunch of vignettes? 

Related: #332. `drake` started with a bunch of vignettes, but they got too cumbersome. `devtools::build()` took a long time, and there were a lot of `Suggests:` packages that were only needed for the examples in the vignettes. In addition, I needed to do some awkward trickery to get the embedded HTML widgets to render on CRAN without increasing the installed size beyond 5 MB. Offloading to `bookdown` really helped development. 

I suppose if we really wanted to merge the manual with the `pkgdown` site, we could just `.Rbuildignore` most of the vignettes. I am still willing to consider it, but for now, I prefer the separation between `drake` itself and the long-form documentation. I think it is conceptually convenient, and the Travis build/deployment times are lower than otherwise.

**Comment by maelle** [comment]
> From left to right, I think we could have these navbar links:

Sounds good, maybe make "Resources links" "Resources" to win space?

Thanks for the discussion of bookdown, it makes sense. :ok_hand: I might use these points (with attribution!) in a blog post about package docs some day.

**Comment by wlandau** [comment]
Sounds good, thanks for the suggestions.
