### ISSUE TITLE
Target that depends on Rcpp functions never up to date

### ISSUE THREAD

**Issue by LDalby** [ropensci/drake#806]
First of all thanks for the great work on this package! This will be a game changer for the work I do in R!

I have a plan where one of the targets are made by a function which in turn uses a number of cpp functions which are sourced in the master script. Somehow this target is never *Up to date* which of course causes everything downstream also be rebuilt every time the plan is run.

Is there a trick to get around this?

**Comment by wlandau** [comment]
Would you post a [`reprex`](https://github.com/tidyverse/reprex)? It would be helpful to get a sense of how you are compiling the C++ functions.

**Comment by wlandau** [comment]
The problem comes from how R represents C++ functions compiled inline.

``` r
f <- Rcpp::cppFunction(
  "int add(int x, int y, int z) {
      int sum = x + y + z;
      return sum;
    }"
)

deparse(f)
#> [1] "function (x, y, z) "                      
#> [2] ".Call(<pointer: 0x7f29058c22e0>, x, y, z)"
```

<sup>Created on 2019-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The "<pointer: 0x7f29058c22e0>" is unavoidably different for each R session. Effective https://github.com/ropensci/drake/commit/8addf5c4845c5e95ed7e2c9422a231ad25773484, `drake` now subs out "<pointer: 0x[0-9a-zA-Z]*>" from the deparsed functions that it tracks for changes.
