### ISSUE TITLE
use `tidyselect` to select targets to make?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#810]
- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

Ref #591 #209 #263 

Would be good to be able to do things like: `targets = matches("this_type_of_target")` in `make`.

**Comment by wlandau** [comment]
Gosh, that would be super convenient! Unfortunately, however, `tidyselect::vars_select()` is designed to accept informal arguments in `...` rather than a single vector / formal argument. To use `tidyselect` on the `targets` argument of `make()`, we would have to splice it into `vars_select()`. Not only is this difficult, awkward, and error prone, it also does not get us the full flexibility of `tidyselect`, e.g. multiple selectors:

``` r
library(tidyverse)
select(mtcars, starts_with("mpg"), ends_with("cyl")) %>%
  head
#>                    mpg cyl
#> Mazda RX4         21.0   6
#> Mazda RX4 Wag     21.0   6
#> Datsun 710        22.8   4
#> Hornet 4 Drive    21.4   6
#> Hornet Sportabout 18.7   8
#> Valiant           18.1   6
```

<sup>Created on 2019-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Thinking back, I am not even sure #209 was an appropriate use of `tidyselect`. Those select helpers were originally designed to select columns of data frames, which is not what we are doing in `drake`'s API functions. If there is ever some sort of analogous "tidy filter" functionality, that would suit `drake` better.
