### ISSUE TITLE
Plan should be out-of-date but isn't

### ISSUE THREAD

**Issue by ldecicco-USGS** [ropensci/drake#828]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [ ] Consider instead posting to [Stack Overflow](https://stackoverflow.com) under the [`drake-r-package` tag](https://stackoverflow.com/tags/drake-r-package).
I'll post if you'd prefer, just close this issue....

## Question

I feel like I had this figured out once, but now I'm getting it wrong again....but somehow I'm missing the answer in my searches. So...apologizes if you've answered this question even *to me* already. Let's say I generate a file, and then somehow delete that file outside of R (like in Windows explorer or something). How can I get `drake` to realize I need to update that target? My example:

```r
library(drake)
options(drake_make_menu = FALSE)
pkgconfig::set_config("drake::strings_in_dots" = "literals")

file_out_data <- "test.xlsx"

data_setup_plan <- drake_plan(
  mtcars = mtcars[-1,-1],
  saveOutput = openxlsx::write.xlsx( mtcars, file = file_out(file_out_data))
)

make(data_setup_plan)
config <- drake_config(data_setup_plan)
vis_drake_graph(config, build_times = "none")

```
So far so good:
![image](https://user-images.githubusercontent.com/1105215/55738307-7b761180-59ec-11e9-8466-b6afefdf91a2.png)

But now I delete  "test.xlsx", and re-run `make(data_setup_plan)`, but it still thinks it's up-to-date, so it doesn't re-create the "test.xlsx".

**Comment by wlandau** [comment]
Yes, this one regularly comes up, and it may seem a bit strange. To learn about your dependencies, `drake` analyzes the code in the plan before it runs or evaluates anything. That means `file_out()` needs to have literal character strings instead of variables that contain them. In other words, `file_out(file_out_data)` does not work, but `file_out("test.xlsx")` does. There are a couple ways to handle this.

## 1. Literally write "test.xlsx"

``` r
library(drake)
options(drake_make_menu = FALSE)
# No need for strings_in_dots = "literals" in version >= 7.0.0.

data_setup_plan <- drake_plan(
  mtcars = mtcars[-1, -1],
  saveOutput = openxlsx::write.xlsx(mtcars, file = file_out("test.xlsx"))
)

make(data_setup_plan)
#> target mtcars
#> target saveOutput
#> Note: zip::zip() is deprecated, please use zip::zipr() instead
#> Target saveOutput messages:
#>   Note: zip::zip() is deprecated, please use zip::zipr() instead
config <- drake_config(data_setup_plan)
vis_drake_graph(config, build_times = "none")
```

![](https://i.imgur.com/SozsKLB.png)

<sup>Created on 2019-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## 2. Use tidy evaluation

Tidy evaluation can pre-compute stuff for the plan.

``` r
library(drake)
options(drake_make_menu = FALSE)
# No need for strings_in_dots = "literals" in version >= 7.0.0.

file_out_data <- "test.xlsx"

data_setup_plan <- drake_plan(
  mtcars = mtcars[-1, -1],
  saveOutput = openxlsx::write.xlsx(
    mtcars,
    file = file_out(!!file_out_data) # See the tidy_eval arg of drake_plan()
  )
)

make(data_setup_plan)
#> target mtcars
#> target saveOutput
#> Note: zip::zip() is deprecated, please use zip::zipr() instead
#> Target saveOutput messages:
#>   Note: zip::zip() is deprecated, please use zip::zipr() instead
config <- drake_config(data_setup_plan)
vis_drake_graph(config, build_times = "none")
```

![](https://i.imgur.com/h4zsf9D.png)

<sup>Created on 2019-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ldecicco-USGS** [comment]
GAH, yup, I think I've even asked you this. Thanks!
