### ISSUE TITLE
Hardcode cpu=1 for r_vis_drake_graph() and friends?

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#842]
When using `r_vis_drake_graph()` in my HPC driven project, the function usually takes whats specified in `drake_config()`. I usually have there `jobs = >1` and `n_cpus > 10`. 

Every time I run `r_vis_drake_graph()` it also spawns > 10 workers even though sequential execution would suffice in this case. Can we/should we adjust `n_cpus` in the background for `r_vis_drake_graph()`?

With the danger of some workers not terminating with `callr` sometimes, I would really like to avoid this "danger" of zombie processes.

```r
r_vis_drake_graph()
Error while shutting down parallel: unable to terminate some child processes
```

```r
drake_config(benchmark_plan, verbose = 2, parallelism = "clustermq", jobs = 2,
             template = list(n_cpus = 17, memory = 34000, log_file = "worker%a.log"), 
             console_log_file = "drake.log")
```

**Comment by wlandau** [comment]
Hmm...`n_cpus` should only come into play for `make()`. I suspect the visualizations are using `config$jobs` where they should be using `config$jobs_preprocess` and those zombies are adding up.

**Comment by wlandau** [comment]
@pat-s, would you try https://github.com/ropensci/drake/commit/116abd4765dbd3d2296835af3eefeb80187e7994? I substituted in `config$jobs_preprocess` in for `config$jobs` in several places. Since `jobs_preprocess` is 1 for you, `r_vis_drake_graph()` should no longer be generating so many extra processes.

**Comment by wlandau** [comment]
I did some local testing on [`drake_example("main")`](https://github.com/wlandau/drake-examples/tree/master/main), and I think the problem is gone. I modified the [last part of `_drake.R`](https://github.com/wlandau/drake-examples/blob/03331e6822e0bc48871f40b343a8932ce4957f32/main/_drake.R#L16) to be

```r
options(clustermq.scheduler = "multicore")
drake_config(plan, parallelism = "clustermq", jobs = 16)
```

and `r_vis_drake_graph()` only spawns one other R process in the latest commit.

**Comment by pat-s** [comment]
Thanks! Message is gone and I think execution also became faster now. Most likely because not so many workers are spawned.
