### ISSUE TITLE
Efficient track of parameters/ artifacts for different models

### ISSUE THREAD

**Issue by nettoyoussef** [ropensci/drake#891]
## Question
 
Hi guys, how are you?
I'm pretty newbie with drake, so forgive me if this was asked before. I took a look at the books, the vignettes and the docs but couldn't found anything that would exactly suit my needs.

While drake makes an excellent job tracking the plan to run a particular analysis, I am thinking in ways more focused to track results and parameters of particular pieces of a DAG. 

In my problem, I am working with several ML models which can be fed different features extracted from the same dataset. So I may in one experiment use a particular subdataset with, say, a 100 variables, and in another experiment use one with 300. 

Besides that, I can still change models (algorithms), and parameters inside the same model.

So my question is: is there a way to log parameters and datasets fed to a model out of the box with drake or do I have to create my own solution?

I'm thinking something in the style that MLflow provides, when I just flag the parameter that I want to save and they register it with the duration time of the experiment, and the metrics flagged to evaluate the model (e.g., AUC, F1-score etc). 

See a example here:
https://docs.azuredatabricks.net/applications/mlflow/tracking.html

Thanks in advance!

**Comment by wlandau** [comment]
`drake` does not natively support MLflow-like tracking, but I suspect you can use MLflow itself within a `drake` project. `drake` could not only save time but also help you avoid overburdening the MLflow logs with redundant model runs. Tentative sketch:

``` r
library(drake)
library(keras)
library(mlflow)
library(rsample)
library(tidyverse)

run_my_model <- function(data, vars) {
  # Set up an experiment?
  model <- fit_my_keras_model(training(data), vars)
  mlflow_log_param("vars", vars)
  get_model_accuracy(model, data) %>%
    mlflow_log_metric("accuracy")
  # Other logging and tracking here.
  serialize_model(model) # So drake can save the model.
}

plan <- drake_plan(
  data = read_data(file_in("example.csv")) %>%
    initial_split(prop = 0.3),
  model = target(
    run_my_model(data, vars),
    transform = map(vars = c(100, 300))
  )
)

plan
#> # A tibble: 3 x 2
#>   target    command                                                        
#>   <chr>     <expr>                                                         
#> 1 data      read_data(file_in("example.csv")) %>% initial_split(prop = 0.3)
#> 2 model_100 run_my_model(data, 100)                                        
#> 3 model_300 run_my_model(data, 300)
```

<sup>Created on 2019-05-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@r-clements was going to give a [talk on `drake` and MLflow](https://www.evensi.us/workflow-management-drake-mlflow-robert-technologies/304322750) earlier this month, but it was rescheduled due to illness. I am curious about what he thinks.

Without MLflow, you would need custom code to track specialized target metadata. You can work with the output of `drake_plan(..., trace = TRUE)`, which adds special columns to the plan for grouping variables you define for [transformations](https://ropenscilabs.github.io/drake-manual/plans.html#large-plans).

``` r
library(drake)
drake_plan(
  data = read_data(file_in("example.csv")) %>%
    initial_split(prop = 0.3),
  model = target(
    run_my_model(data, vars),
    transform = map(vars = c(100, 300))
  ),
  trace = TRUE
)
#> # A tibble: 3 x 4
#>   target    command                                           vars  model  
#>   <chr>     <expr>                                            <chr> <chr>  
#> 1 data      read_data(file_in("example.csv")) %>% initial_sp… <NA>  <NA>   
#> 2 model_100 run_my_model(data, 100)                         … 100   model_…
#> 3 model_300 run_my_model(data, 300)                         … 300   model_…
```

<sup>Created on 2019-05-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
FYI: I think this is actually possible in `drake`, and I am working on it right now in #918. If all goes well, tracking of parameters will be implicit and automatic. E.g. if you write something like `drake_plan(y = f(g(x = 1, y = 2), z = 3)`, `drake` should just tell you that `x` is 1, `y` is 2, and `z` is 3. The static code analysis for this is actually straightforward.

**Comment by wlandau** [comment]
Now implemented: https://github.com/ropensci/drake#history-and-provenance
