### ISSUE TITLE
Feature Request: Auto-Clean Targets not Built

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#916]
I recently had an issue where I was accidentally building based on a target that was no longer named in my plan.

As an example, I did something like the following (far simplified from the real case):

```r
make(drake_plan(a=1))
make(drake_plan(b=a+1))
```

I would find it helpful if there were an option to either `make()` or `clean()` that would clean any targets that were not in the plan.  I could imagine an interface that would look something like:

```r
clean(except=drake_plan(b=a+1))
```

where it would remove any targets that were not targets in the specified plan (`a` in this case).

To be very clear, I think that the current behavior where it is allowed to make only parts of the plan at a time is very useful, and I would not want to change the default.

**Comment by wlandau** [comment]
How about this?

``` r
 library(drake)

plan <- drake_plan(x = 1, y = 1, z = 1)

make(plan)
#> target x
#> target y
#> target z

cached()
#> [1] "x" "y" "z"

plan <- drake_plan(x = 1, y = 2)
remove_these <- setdiff(cached(), plan$target)
clean(list = remove_these)

cached()
#> [1] "x" "y"
```

<sup>Created on 2019-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
That is simple and works well.  Thanks!

**Comment by wlandau** [comment]
Sure.

I almost forgot to mention: cleaning does not actually remove the data from storage. For that to happen, you can either call `clean(garbage_collection = TRUE)` or `clean(...); drake_cache()$gc()`.

**Comment by brendanf** [comment]
I know this is closed, but I'm curious how the `n-<hash>` and `p-<hash>` values in the cache work related to this.  I think (some of them? the `p`'s?) are related to input and output files.  Is there a way to figure out which ones represent files that are no longer in the plan?

**Comment by wlandau** [comment]
The `n-<stuff>` and `p-<stuff>` denote namespaced functions (`pkg::fun()`) and file paths, respectively. The `<stuff>` is actually a Base32-encoded string of variable length. (Unfortunately, we cannot use a hash function because we need to be able to invert `<stuff>` and turn it back into the original names.) The reason we do this because those strings become the names key files in `storr_rds()` caches, and "pkg::fun" and "/dir/dir/file/data.csv" are illegal file names. Previously, `drake` just used `storr_rds(mangle_key = TRUE)`, but that was too slow because it mangled all the keys. `drake` does its own key mangling now, and only on the keys that actually need it.

I tried to hide this from the user. You can call file_store() as a wrapper, and `base64url::base32_decode()` goes in reverse.

``` r
drake::file_store("/my_dir/dir/dir/my_file.txt")
#> [1] "p-F5WXSX3ENFZC6ZDJOIXWI2LSF5WXSX3GNFWGKLTUPB2A"
base64url::base32_decode("F5WXSX3ENFZC6ZDJOIXWI2LSF5WXSX3GNFWGKLTUPB2A")
#> [1] "/my_dir/dir/dir/my_file.txt"
```

<sup>Created on 2019-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
