### ISSUE TITLE
Use of drake in a R Package

### ISSUE THREAD

**Issue by sankarbsubramani** [ropensci/drake#976]
Hello Everyone,

I am new to R and have just come across drake. I am currently involved in the process of parallezing a R package.

My question : 
1. Is it possible to use drake in a library, especially in the case of a parallel backends to accelerate certain portions of the function ?
2. Are there any examples or projects that you are aware of that utilizes such a strategy ?
3. Do you forsee any pitfalls in such an approach ?

Thank you in advance for your replies.

**Comment by wlandau** [comment]
Welcome, @sankarbsubramani. Good questions.

Some users do implement `drake` workflows as packages. @tiernanmartin maintains an archetype of this at https://github.com/tiernanmartin/drakepkg. The R package structure turns out to be convenient for containing the `drake_plan()` and supporting functions of a workflow, and it is a useful vehicle for documentation and automated testing.

`drake`'s parallel computing is designed to operate at the highest level of a project. In other words, instead of parallelizing inner portions of a function body, it operates *outside* your functions to run function calls simultaneously. Details: https://ropenscilabs.github.io/drake-manual/hpc.html.

If you goal is to parallelize the inside of a function, I recommend [`furrr`](https://github.com/DavisVaughan/furrr), which is based on [`future`](https://github.com/HenrikBengtsson/future) and inspired by [`purrr`](https://github.com/tidyverse/purrr). It is lightweight, and you can put calls to `furrr::future_map()` and friends inside your own custom functions. How it works:

``` r
library(furrr)
#> Loading required package: future
library(future.callr) # One possible parallel backend for future

get_pid
#> Error in eval(expr, envir, enclos): object 'get_pid' not found

# Register a parallel backend with 2 local processes.
future::plan(callr, workers = 2)

# Run 100 tasks.
pids <- furrr::future_map_int(
  .x = seq_len(100),
  .f = function(x) {
    # Ordinarily, this function would contain some data processing work,
    # but let's just return the process ID of the worker.
    Sys.getpid()
  }
)

# How did we split up the work?
table(pids)
#> pids
#> 54277 54284 
#>    50    50
```

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sankarbsubramani** [comment]
Thank you so much for your quick and deatiled reply. This is most helpful.
